import type { Metadata } from "next";
import Link from "next/link";
import { Arrow, Brand, Footer } from "@/components/bendalabs/brand-shell";
import AutomationPreview from "@/components/bendalabs/automation-preview";
import AutomationConfigurator from "@/components/bendalabs/automation-configurator";
import { automationModules, euro, readAutomationModules } from "@/lib/bendalabs/automation";
import "./automation.css";

export const metadata: Metadata = {
  title: "Doklady raz. Zmluvy a dodatky bez prepisovania | BendaLabs",
  description: "Načítanie údajov z dokladov, nástupné dokumenty aj personalizované dodatky z uložených údajov. Vytvoríme firemný systém podľa vašich postupov. Dokumenty od 950 € + 44,50 € mesačne.",
  alternates: { canonical: "https://bendalabs.sk/automatizacia" },
  openGraph: { title: "Doklady nahrajte raz. Zmluvy a dodatky už neprepisujte.", description: "Firemné dokumenty z uložených údajov. Váš tím, vaše vzory a vlastný prehľad. Nastavenie od 950 € + prevádzka od 44,50 € mesačne.", url: "https://bendalabs.sk/automatizacia", locale: "sk_SK", type: "website" },
};

const faqs = [
  ["Čo znamená, že si systém údaje pamätá?", "Po načítaní a potvrdení sa potrebné údaje uložia do profilu zamestnanca, klienta alebo firmy. Pri ďalšej zmluve či dodatku vyberiete tento profil a doplníte iba nové informácie. Tie isté doklady znova nenahrávate. Ak sa údaje zmenia, aktualizujete ich v profile."],
  ["Aké doklady a dokumenty môžeme používať?", "Napríklad občiansky preukaz, živnostenské oprávnenie, existujúce zmluvy alebo firemné formuláre vo forme PDF, skenu či fotografie. Na vašich podkladoch nastavíme, ktoré údaje sa majú načítať a v akých dokumentoch sa použijú. Firemné vzory môžeme spojiť do celého nástupného balíka."],
  ["Budeme mať vlastný systém a prístupy pre tím?", "Áno. Vaša firma dostane vlastný pracovný priestor s prehľadom ľudí, firiem a dokumentov. Spolu určíme, kto má k jednotlivým údajom prístup a ako sa má pracovať s nahranými podkladmi. Jednotlivé funkcie nastavíme podľa vašich postupov."],
  ["Kto kontroluje pripravené dokumenty?", "Systém doplní údaje do vašich schválených vzorov. Načítané údaje aj výsledné dokumenty si môžete skontrolovať pred použitím. Váš tím tak rozhoduje o finálnom obsahu, zatiaľ čo systém vybaví opakované vypĺňanie."],
  ["Ako bude systém vyhľadávať zákazky?", "Spoločne nastavíme odbor, región a typ príležitostí, ktoré majú pre vás zmysel. Vyberieme a preveríme vhodné zdroje. Systém ich bude pravidelne sledovať a ukladať nájdené príležitosti spolu s odkazmi a dostupnými podmienkami do vášho prehľadu."],
  ["Ako funguje cena a mesačná prevádzka?", "Uvedené ceny sú uvádzacie pre prvých päť klientov a začínajú na zobrazenej sume. Konkrétnu cenu potvrdíme podľa vašich dokumentov a pracovného postupu pred začiatkom. Jednorazovo platíte vytvorenie a nastavenie: 50 % na začiatku a 50 % po odovzdaní. Mesačná cena zahŕňa dohodnutú prevádzku, hosting, zálohy a opravy chýb; začne sa účtovať po odovzdaní."],
  ["Môžeme začať jednou úlohou a neskôr systém rozšíriť?", "Áno. Môžeme začať napríklad nástupnými dokumentmi a neskôr doplniť ďalší firemný postup alebo vyhľadávanie zákaziek. Do formulára môžete napísať aj požiadavku mimo ponuky. Navrhneme riešenie a cenu ešte pred realizáciou."],
];

export default async function AutomationPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const params = await searchParams;
  const initialModules = readAutomationModules(params.modul);
  return <div className="bl-site auto-site"><a href="#main" className="bl-skip">Prejsť na obsah</a>
    <header className="auto-header"><div className="bl-wrap auto-header-inner"><Brand /><nav aria-label="Navigácia ponuky"><a href="#ako-to-funguje">Ako to funguje</a><a href="#moduly">Čo ponúkame</a><a href="#konfigurator">Cena</a></nav><a className="bl-button bl-button-small" href="#konfigurator">Mám záujem <Arrow /></a></div></header>
    <main id="main">
      <section className="auto-hero bl-wrap"><div className="auto-hero-copy"><p className="auto-kicker"><span aria-hidden="true" /> Firemný systém podľa vašich postupov</p><h1>Doklady<br />nahrajte raz.<br /><span>Zmluvy a dodatky<br />už neprepisujte.</span></h1><p className="auto-lead">Vytvoríme vám systém, ktorý načíta údaje z dokladov, zapamätá si ich a použije ich v zmluvách, dodatkoch aj nástupných dokumentoch.</p><div className="auto-hero-actions"><a className="bl-button" href="#konfigurator">Chcem ušetriť ručnú prácu <Arrow /></a><a className="bl-text-link" href="#ako-to-funguje">Ako to funguje <span aria-hidden="true">↓</span></a></div><div className="auto-hero-price"><strong>Od 950 €</strong><span>nastavenie dokumentového systému<br />+ od 44,50 € mesačne za prevádzku</span></div><p className="auto-intro-note">Uvádzacia ponuka pre prvých 5 klientov.</p></div><AutomationPreview /></section>
      <div className="auto-promise-strip"><div className="bl-wrap"><p><span aria-hidden="true">✓</span> Menej opakovaného vypĺňania</p><p><span aria-hidden="true">✓</span> Menej priestoru na preklepy</p><p><span aria-hidden="true">✓</span> Viac času na prácu s ľuďmi</p></div></div>
      <section className="auto-how bl-wrap" id="ako-to-funguje">
        <div className="auto-heading-row"><div><p className="bl-eyebrow">Od dokladu k hotovým podkladom</p><h2>Údaje už máte.<br />Používajte ich znova.</h2></div><p>Meno, adresu či údaje firmy nemusíte kopírovať do každého súboru. Systém ich doplní tam, kde ich potrebujete.</p></div>
        <ol className="auto-workflow">
          <li><span className="auto-step-number">01</span><h3>Nahrajte podklady</h3><p>Občiansky preukaz, živnostenské oprávnenie alebo iný dokument. Systém z neho načíta potrebné údaje.</p><span className="auto-step-outcome">Z dokladu do profilu</span></li>
          <li><span className="auto-step-number">02</span><h3>Vyberte, čo potrebujete</h3><p>Nástupný balík, zmluvu či dodatok. Doplníte iba nové informácie, napríklad pozíciu, odmenu alebo dátum.</p><span className="auto-step-outcome">Vaše údaje + vaša šablóna</span></li>
          <li><span className="auto-step-number">03</span><h3>Skontrolujte dokumenty</h3><p>Systém pripraví vyplnené podklady. Pri ďalšom dokumente už vyberiete uloženého človeka alebo firmu.</p><span className="auto-step-outcome">Bez opätovného nahrávania</span></li>
        </ol>
        <div className="auto-cases-heading"><p className="bl-eyebrow">Príklady z bežného dňa vo firme</p><h2>Kde vám to uľahčí prácu?</h2></div>
        <div className="auto-cases">
          <article><span className="auto-case-label">Keď nastupuje zamestnanec</span><h3>Celý nástupný balík<br />z jedného profilu.</h3><p>Načítate údaje z dokladov, doplníte pracovné podmienky a pripravíte zmluvu, osobný dotazník aj ďalšie dokumenty používané pri nástupe.</p><div><span aria-hidden="true">↗</span> Rovnaké údaje vo všetkých podkladoch.</div></article>
          <article><span className="auto-case-label">Keď sa menia podmienky</span><h3>Dodatok bez hľadania<br />starých súborov.</h3><p>Vyberiete zamestnanca alebo klienta a zadáte zmenu. Systém doplní jeho uložené údaje a pripraví personalizovaný dodatok k zmluve.</p><div><span aria-hidden="true">↗</span> Vypĺňate iba to, čo sa zmenilo.</div></article>
          <article><span className="auto-case-label">Keď pripravujete ďalšiu zákazku</span><h3>Klienta už poznáte.<br />Údaje už máte.</h3><p>Z uloženého profilu firmy pripravíte ďalšiu zmluvu, objednávku, potvrdenie či odovzdávací protokol podľa vašich firemných vzorov.</p><div><span aria-hidden="true">↗</span> Menej kopírovania medzi dokumentmi.</div></article>
        </div>
      </section>
      <section className="auto-modules" id="moduly"><div className="bl-wrap"><div className="auto-heading-row"><div><p className="bl-eyebrow">Vyberte si, s čím začneme</p><h2>Dve služby.<br />Váš vlastný systém.</h2></div><p>Automatizujte dokumenty, hľadanie zákaziek alebo oboje. Služby môžu fungovať spolu v jednom firemnom priestore.</p></div><div className="auto-module-grid">{automationModules.map(module => <article key={module.id} className="auto-module-card"><div className="auto-module-number"><span>SLUŽBA {module.number}</span><ModuleIcon id={module.id} /></div><h3>{module.title}</h3><p>{module.description}</p><ul>{module.benefits.map(line => <li key={line}>{line}</li>)}</ul><div className="auto-module-price"><span>Vrátane vlastného firemného priestoru</span><strong><small>od </small>{euro(module.totalSetup)}<small> jednorazovo</small></strong><p>+ od {euro(module.totalMonthly)} / mesiac</p></div><Link href={`/automatizacia?modul=${module.id}#konfigurator`} className="bl-text-link">{module.id === "dokumenty" ? "Chcem automatizovať dokumenty" : "Chcem vyhľadávať zákazky"} <Arrow /></Link></article>)}</div><p className="auto-modules-note">Uvádzacie ceny pre prvých 5 klientov. Konkrétne riešenie a cenu potvrdíme podľa potrieb vašej firmy.</p></div></section>
      <section className="auto-dashboard-section"><div className="bl-wrap auto-dashboard-grid"><div><p className="bl-eyebrow">Vlastný prehľad pre váš tím</p><h2>Ľudia, údaje a dokumenty.<br />Konečne spolu.</h2><p>Každá firma dostane svoj dashboard. Pri človeku či firme nájdete uložené údaje aj súvisiace dokumenty. Váš tím bude vedieť, kde pokračovať.</p><a href="#ukazka" className="bl-text-link">Vyskúšať ukážku <Arrow /></a></div><div className="auto-dashboard-features"><div><span aria-hidden="true">↻</span><div><h3>Údaje, ku ktorým sa vrátite</h3><p>Vyberiete uložený profil. Ďalšia zmluva alebo dodatok už nezačína od nuly.</p></div></div><div><span aria-hidden="true">□</span><div><h3>Rovnaký postup pre celý tím</h3><p>Spoločné firemné vzory, história dokumentov a prístupy podľa úloh vašich ľudí.</p></div></div><div><span aria-hidden="true">+</span><div><h3>Začnete tým, čo potrebujete dnes</h3><p>Ďalšie postupy doplníme podľa vašich reálnych potrieb. Vlastnú požiadavku môžete napísať hneď.</p></div></div></div></div></section>
      <AutomationConfigurator key={initialModules.join(",")} initialModules={initialModules} />
      <section className="auto-process bl-wrap"><div className="auto-heading-row"><div><p className="bl-eyebrow">Nastavenie vybavíme s vami</p><h2>Vy poznáte svoju prácu.<br />My nastavíme systém.</h2></div><p>Vychádzame z dokumentov a krokov, ktoré vo firme používate. Systém vám odovzdáme aj s vysvetlením pre váš tím.</p></div><ol className="auto-process-grid">{[["Opíšete nám svoju úlohu", "Čo dnes robíte ručne a čo by mal systém pripraviť za vás."], ["Ukážete nám príklad", "Prejdeme vaše podklady a navrhneme konkrétny postup aj cenu."], ["Nastavíme a vyskúšame", "Riešenie overíme na vašich príkladoch a doladíme spolu s vami."], ["Začnete ho používať", "Dostanete vlastný firemný priestor a zaškolenie. O prevádzku sa postaráme."]].map(([title, copy], index) => <li key={title}><span>0{index + 1}</span><h3>{title}</h3><p>{copy}</p></li>)}</ol></section>
      <section className="auto-faq bl-wrap"><div><p className="bl-eyebrow">Čo vás môže zaujímať</p><h2>Praktické otázky.</h2><p>Radšej osobne?<br /><a href="mailto:info@bendalabs.sk">info@bendalabs.sk ↗</a></p></div><div>{faqs.map(([question, answer]) => <details key={question}><summary>{question}<span aria-hidden="true">+</span></summary><p>{answer}</p></details>)}</div></section>
      <section className="auto-final-cta"><div className="bl-wrap"><p className="bl-eyebrow">Začnite jednou opakujúcou sa úlohou</p><h2>Čo už nechcete<br />vypĺňať stále dookola?</h2><a href="#konfigurator" className="bl-button">Navrhnite mi automatizáciu <Arrow /></a><p>Marek Benda · BendaLabs · <a href="tel:+421944388123">+421 944 388 123</a></p></div></section>
    </main><Footer />
  </div>;
}

function ModuleIcon({ id }: { id: string }) {
  return <svg width="27" height="27" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.4" aria-hidden="true">{id === "dokumenty" ? <path d="M6 3h8l4 4v14H6zM14 3v5h5M9 12h6M9 16h6" /> : <><circle cx="10" cy="10" r="6" /><path d="m15 15 6 6M7 10h6M10 7v6" /></>}</svg>;
}
