import type { LeadFormSharedCopy } from "./lead-form-content";
export const englishLeadForm: LeadFormSharedCopy = {
  fields: { name: "Name", email: "Email", website: "Website", message: "What would you like to improve?", source: "Source" },
  placeholders: { name: "Your name", email: "you@company.com", website: "https://yourcompany.com", message: "Briefly describe where visitors get stuck or what should be easier.", phone: "+44 7700 900000", preferredTime: "For example, Tuesday 10:00–12:00, including your time zone", note: "Add any useful context or a question (optional)." },
  callFields: { phone: "Phone", preferredTime: "Preferred time", emailOptional: "Email (optional)", note: "Short note (optional)", website: "Audited website", websiteFallback: "Website" },
  validation: { required_name: "Enter your name.", invalid_name: "Enter a valid name.", required_email: "Enter your email address.", invalid_email: "Enter a valid email address.", required_website: "Enter a website or domain.", invalid_website: "Enter a valid website or domain.", required_message: "Enter your message.", invalid_message: "Your message must contain at least 10 characters.", invalid_source: "We could not identify the enquiry source. Please reload the page and try again." },
  genericErrorMessage: "Your enquiry could not be sent. Please try again.",
  audit: { badge: "A specific proposal", title: "Send your details and request a proposal", description: "Send your contact details and goals. I will suggest where an AI layer could make the most sense for your website.", submitLabel: "Send enquiry", submittingLabel: "Sending…", successTitle: "Thank you. Your enquiry has been sent.", successMessage: "I will be in touch with a proposal for your website." },
  contact: { badge: "INTERESTED IN AN AI LAYER FOR YOUR WEBSITE?", title: "Send your website and business goal", description: "Briefly explain what the website should do better or where visitors drop off.", submitLabel: "Send enquiry", submittingLabel: "Sending…", successTitle: "Thank you. Your enquiry has been sent.", successMessage: "I will be in touch about the next step." },
  call: { badge: "A short call", title: "Arrange a short call", description: "Leave your contact details and preferred time. We will get in touch to discuss where an AI layer could be useful.", submitLabel: "Request a call", submittingLabel: "Sending…", successTitle: "Thank you. Your call request has been sent.", successMessage: "We will be in touch about the next step." },
  sourceLabels: { audit_result: "After an audit", contact_section: "Contact", ai_navrh_na_mieru: "Custom AI proposal" },
};
