import type { SiteLocale } from "./site-content";

const copy: Record<string, string> = {
  "Zadajte platnú webovú adresu. Stačí aj doména ako vasweb.sk.": "Enter a valid website address. A domain such as yourcompany.com is enough.",
  "Vyberte, aký typ webu riešite.": "Choose the type of website you want to improve.",
  "Vyberte, čo má AI vrstva zlepšiť ako prvé.": "Choose what the AI layer should improve first.",
  "Vyberte, čo má návštevník ideálne spraviť.": "Choose the action you would ideally like visitors to take.",
  "Stručne doplňte, kde dnes vidíte najväčšiu príležitosť na zlepšenie.": "Briefly describe the biggest opportunity for improvement you see today.",
  "Vyberte aspoň jeden typ dát, ktorý chcete vidieť v dashboarde.": "Select at least one type of data you would like to see in the dashboard.",
  "Doplňte, podľa čoho by ste po 30 dňoch povedali, že to má zmysel.": "Describe how you would judge success after 30 days.",
  "Zadajte platný email.": "Enter a valid email address.",
  "Web nie je platný. Vráťte sa na prvý krok a opravte ho.": "The website address is invalid. Return to the first step and correct it.",
  "Návrh sa teraz nepodarilo pripraviť. Skontrolujte vyplnené údaje.": "We could not prepare the proposal. Please check your answers.",
  "Návrh sa zobrazil, ale kontakt sa nepodarilo uložiť. Napíšte nám na info@bendalabs.sk.": "Your proposal is ready, but your contact details could not be saved. Please email info@bendalabs.sk.",
  "Návrh pripravený": "Proposal ready",
  "Váš AI návrh na mieru": "Your custom AI proposal",
  "Odporúčaný typ AI vrstvy": "Recommended type of AI layer",
  "Dohodnúť krátky call": "Arrange a short call",
  "AI návrh na mieru — ": "Custom AI proposal — ",
  "Konzultovať návrh e-mailom": "Discuss the proposal by email",
  "Kontakt bol odoslaný.": "Your contact details have been sent.",
  "Upraviť zadanie": "Edit your answers",
  "Zadanie": "Your brief",
  "Web": "Website",
  "Typ webu": "Website type",
  "Hlavný cieľ": "Main goal",
  "Ideálny ďalší krok návštevníka": "The visitor's ideal next step",
  "Čo by riešila pre návštevníka": "How it could help visitors",
  "Čo by získal váš tím": "What your team could gain",
  "Aké dáta by ukázal dashboard": "What the dashboard could show",
  "Najjednoduchšia prvá fáza": "A practical first phase",
  "Odporúčaný ďalší krok": "Recommended next step",
  "AI návrh na mieru": "Custom AI proposal",
  "Odpovedzte na pár otázok o vašom webe a cieľoch. Na konci získate návrh, aká AI vrstva by mohla dávať najväčší zmysel práve pre váš biznis.": "Answer a few questions about your website and goals. You will receive a proposal for the AI layer that could make the most sense for your business.",
  "návrh na mieru": "custom proposal",
  "lepšie pripravené dopyty": "better-prepared enquiries",
  "dashboard zámerov": "visitor intent dashboard",
  "bez prerábky existujúceho webu": "works over your existing website",
  "Krok": "Step",
  "z 8": "of 8",
  "Čo získate": "What you receive",
  "Na konci uvidíte odporúčaný typ AI vrstvy, čo by riešila pre návštevníka, aké nové obchodné dáta by ste vedeli sledovať a aký je najjednoduchší prvý krok.": "See a suggested AI layer, how it could help visitors, which business insights you could track and the simplest first step.",
  "Web firmy": "Company website",
  "Aký web chcete posúdiť?": "Which website would you like to assess?",
  "Stačí URL alebo doména. Návrh postavíme na tom, ako dnes funguje váš web a čo od neho potrebujete.": "A URL or domain is enough. The proposal will use your answers about the website and what you need it to achieve.",
  "Typ webu / biznisu": "Website or business type",
  "Aký typ webu riešite?": "What type of website do you have?",
  "Čo by mala AI vrstva zlepšiť ako prvé?": "What should the AI layer improve first?",
  "Ďalší krok návštevníka": "The visitor's next step",
  "Čo má návštevník ideálne spraviť?": "What should the visitor ideally do?",
  "Dnešný problém alebo príležitosť": "Current problem or opportunity",
  "Kde dnes vidíte najväčšiu príležitosť na zlepšenie?": "Where do you see the biggest opportunity for improvement?",
  "Príležitosť na zlepšenie": "Opportunity for improvement",
  "Napr. veľa ľudí píše všeobecné otázky, dopyty sú neúplné, ľudia nevedia vybrať správnu službu, chceme lepšie dáta o zámeroch návštevníkov...": "For example: general questions, incomplete enquiries, difficulty choosing the right service, or a need for better insight into visitor intentions…",
  "Dáta / dashboard": "Data and dashboard",
  "Aké dáta by ste chceli vidieť v dashboarde?": "What would you like to see in the dashboard?",
  "Môžete vybrať viac možností. Cieľom je vidieť, čo ľudia reálne hľadajú a ako sa rozhodujú.": "You can select multiple options. The aim is to understand what people need and how they decide.",
  "Úspech po 30 dňoch": "Success after 30 days",
  "Podľa čoho by ste po 30 dňoch povedali, že to má zmysel?": "How would you know after 30 days that this is worthwhile?",
  "Napr. viac kvalitných dopytov, menej nejasných otázok, lepší prehľad o potrebách zákazníkov, rýchlejšie objednanie...": "For example: more qualified enquiries, fewer unclear questions, better insight into customer needs or faster bookings…",
  "Kontakt": "Contact",
  "Kam vám môžeme poslať návrh alebo sa ozvať?": "Where can we reach you to discuss the proposal?",
  "Meno": "Name",
  "Email": "Email",
  "Telefón (voliteľne)": "Phone (optional)",
  "Firma (voliteľne)": "Company (optional)",
  "Späť": "Back",
  "Ďalší krok": "Next step",
  "Pripravujem návrh...": "Preparing your proposal…",
  "Zobraziť AI návrh na mieru": "Show my custom AI proposal",
  "Zadajte meno.": "Enter your name.",
  "AI vrstva": "AI layer",
  "Odosielam kontakt…": "Sending your contact details…",
  "napr. vasweb.sk": "e.g. yourcompany.com"
};

export function proposalText(locale: SiteLocale, text: string) {
  return locale === "en" ? copy[text] ?? text : text;
}
