import type {Bilingual} from './atlas-data';
const bi=(sk:string,en:string):Bilingual=>({sk,en});
export const plans=[
 {id:'rover',title:bi('Tvoj prvý autonómny rover','Your first autonomous rover'),subtitle:bi('Postav dvojkolesový robot, ktorý zmeria vzdialenosť a vyhne sa prekážke.','Build a two-wheel robot that measures distance and avoids obstacles.'),level:bi('Začiatočník','Beginner'),time:bi('2–3 pracovné večery','2–3 workshop evenings'),lab:'code',materials:[
 {name:bi('Arduino Uno R3 + USB kábel','Arduino Uno R3 + USB cable'),qty:'1',note:bi('5 V logika; tento postup nie je zapojenie pre ESP32.','5 V logic; this wiring is not for ESP32.')},
 {name:bi('TB6612FNG motorový driver','TB6612FNG motor driver'),qty:'1',note:bi('Over schému modulu, prúd motora a tepelný limit.','Check module schematic, motor current and thermal limits.')},
 {name:bi('DC prevodový motor pre 4,8 V','DC geared motor for 4.8 V'),qty:'2',note:bi('Blokovací prúd musí vyhovovať driveru aj pri nižšom napätí.','Stall current must fit driver limits, including at lower voltage.')},
 {name:bi('Podvozok, 2 kolesá a oporné koliesko','Chassis, 2 wheels and a caster'),qty:'1',note:bi('Zhodné kolesá, pevné uchytenie motorov.','Matching wheels, firmly mounted motors.')},
 {name:bi('Ultrazvukový senzor HC-SR04','HC-SR04 ultrasonic sensor'),qty:'1',note:bi('Verzia s 5 V napájaním a Echo výstupom.','Version with 5 V supply and Echo output.')},
 {name:bi('AA NiMH články + držiak 4S','AA NiMH cells + 4S holder'),qty:'4',note:bi('Zhodné nabité články; vhodná externá NiMH nabíjačka.','Matched charged cells; suitable external NiMH charger.')},
 {name:bi('USB 5 V zdroj pre Uno','USB 5 V source for Uno'),qty:'1',note:bi('Regulovaný USB zdroj. Prepojiť spoločnú GND.','Regulated USB source. Connect a common GND.')},
 {name:bi('Vypínač, poistka, vodiče, kondenzátory','Switch, fuse, wires, capacitors'),qty:'1',note:bi('Dimenzovať podľa prúdu a datasheetu drivera.','Size for current and the driver datasheet.')}
 ],steps:[
 {title:bi('Začni požiadavkami a kontrolou komponentov','Start with requirements and component checks'),body:bi('Cieľ: pomalý rover na rovnej podlahe. Zapíš napätie motorov a ich blokovací prúd. Over trvalý prúd TB6612FNG pri najnižšom napätí vybitej motorovej batérie; údaj o špičke nie je trvalý prúd. Skontroluj, či má modul pull-up na STBY. Priprav multimeter, vypínač a poistku motorovej vetvy.','Goal: a slow rover on a flat floor. Record motor voltage and stall current. Check TB6612FNG continuous current at the lowest discharged motor-battery voltage; a peak rating is not a continuous rating. Check whether the module pulls STBY high. Prepare a multimeter, switch and motor-branch fuse.')},
 {title:bi('Zostav podvozok','Assemble the chassis'),body:bi('Motory namontuj súosovo, kolesá sa musia voľne otáčať. Batériu umiestni nízko a upevni ju. Vodiče veď mimo kolies. Senzor upevni vpredu vodorovne; jeho kužeľ merania nesmie zachytávať podlahu alebo vlastný podvozok.','Mount motors on the same axis and make sure wheels spin freely. Position the battery low and secure it. Route wires away from wheels. Mount the sensor horizontally at the front; its measurement cone should avoid the floor and the robot’s own chassis.')},
 {title:bi('Oddeľ logiku a motorový prúd','Separate logic and motor current'),body:bi('Uno napájaj cez USB 5 V. Motorová batéria ide cez poistku a vypínač na VM drivera. VCC drivera a HC-SR04 idú na 5 V z Uno; všetky GND spoj. Motorový prúd nesmie tiecť cez dosku Uno ani nepájivé pole. Pridaj lokálne blokovanie napájania podľa datasheetu. Pred pripojením USB zmeraj polaritu a skraty.','Power Uno through 5 V USB. Route the motor battery through a fuse and switch to driver VM. Connect driver VCC and HC-SR04 to Uno 5 V; join all GND connections. Motor current must not run through Uno or a solderless breadboard. Add local supply decoupling per the datasheet. Check polarity and shorts before connecting USB.')},
 {title:bi('Zapoj signály podľa tabuľky','Connect signals using the table'),body:bi('PWMA → D5, PWMB → D6; AIN1 → D7, AIN2 → D8; BIN1 → D9, BIN2 → D10; STBY → D4. HC-SR04 Trig → D12, Echo → D11. Motor A na AO1/AO2, motor B na BO1/BO2. Pridaj pull-down na STBY, ak ho breakout nemá, a skontroluj konflikt s jeho pull-upom. Toto zapojenie používa výlučne 5 V Uno R3.','PWMA → D5, PWMB → D6; AIN1 → D7, AIN2 → D8; BIN1 → D9, BIN2 → D10; STBY → D4. HC-SR04 Trig → D12, Echo → D11. Motor A connects to AO1/AO2, motor B to BO1/BO2. Add a STBY pull-down if the breakout lacks one and check for conflict with any pull-up. This wiring is exclusively for 5 V Uno R3.')},
 {title:bi('Nahraj kód a testuj s kolesami vo vzduchu','Upload code and test with wheels raised'),body:bi('V Arduino IDE vyber Arduino Uno, port dosky a nahraj vzorový firmvér. Najprv over meranie vzdialenosti v Serial Monitore pri 115200 baud. Potom krátko zapni motory so zdvihnutými kolesami. Over smer; ak je opačný, pri odpojenom napájaní otoč vodiče príslušného motora. Neplatné Echo musí robot zastaviť.','In Arduino IDE select Arduino Uno, the board port and upload the example firmware. First inspect distance readings in Serial Monitor at 115200 baud. Then briefly enable motors with wheels raised. Verify direction; if reversed, disconnect power and swap that motor’s wires. An invalid Echo must stop the robot.')},
 {title:bi('Zmeraj správanie a uprav hranice','Measure behaviour and adjust limits'),body:bi('Na voľnej podlahe začni nízkou rýchlosťou. Zmeraj brzdnú dráhu a uprav hranicu 25 cm s rezervou na oneskorenie merania. Skús mäkkú, šikmú aj úzku prekážku: ultrazvuk ju nemusí spoľahlivo zachytiť. Over odpojený senzor a vypínač. Sleduj zahrievanie a napätie článkov; nevybíjaj batériu až do zastavenia motorov.','Start at low speed on a clear floor. Measure stopping distance and adjust the 25 cm threshold with margin for sensing delay. Test soft, angled and narrow obstacles: ultrasound may miss them. Test a disconnected sensor and the switch. Monitor temperature and cell voltage; do not discharge the battery until the motors stop.')}
 ],sources:[{title:'Arduino Uno R3',url:'https://docs.arduino.cc/hardware/uno-rev3/'},{title:'Toshiba TB6612FNG',url:'https://toshiba.semicon-storage.com/info/docget.jsp?did=10660'},{title:'HC-SR04 · Adafruit',url:'https://learn.adafruit.com/ultrasonic-sonar-distance-sensors/pinouts'}]},
 {id:'ros-rover',title:bi('Rover, ktorý si vytvorí mapu','A rover that builds its own map'),subtitle:bi('Architektúra pre ROS 2, odometriu, LiDAR a navigáciu.','An architecture for ROS 2, odometry, LiDAR and navigation.'),level:bi('Pokročilý','Advanced'),time:bi('Viac víkendov podľa platformy','Several weekends, platform dependent'),lab:'lidar',materials:[
 {name:bi('Počítač s podporovaným Linuxom','Computer with supported Linux'),qty:'1',note:bi('Over kombináciu distribúcie ROS 2 a senzorových ovládačov.','Verify the ROS 2 distribution and sensor driver combination.')},
 {name:bi('Diferenciálny podvozok s enkodérmi','Differential chassis with encoders'),qty:'1',note:bi('Nízkoúrovňová slučka rýchlosti na mikrokontroléri.','Low-level velocity loop on a microcontroller.')},
 {name:bi('2D LiDAR s časovými značkami','2D LiDAR with timestamps'),qty:'1',note:bi('Rozhranie a ovládač pre zvolenú distribúciu.','Interface and driver for the selected distribution.')},
 {name:bi('Napájanie, poistky a fyzické zastavenie','Power, fuses and physical stop'),qty:'1',note:bi('Oddelená motorová a výpočtová vetva.','Separate motor and compute branches.')}
 ],steps:[
 {title:bi('Najprv simulácia','Start in simulation'),body:bi('Vyber podporovanú kombináciu ROS 2, Gazebo, Nav2 a ovládačov. Prvé mapovanie vykonaj v simulácii. Zafixuj verzie, jednotky a konvencie rámcov. Jazzy a Lyrical majú odlišné podporované prostredia; nemiešaj návody bez kontroly verzie.','Choose a supported combination of ROS 2, Gazebo, Nav2 and drivers. Perform the first mapping run in simulation. Pin versions, units and frame conventions. Jazzy and Lyrical support different environments; check versions before combining tutorials.')},
 {title:bi('Kalibruj podvozok a odometriu','Calibrate the chassis and odometry'),body:bi('Zmeraj skutočný priemer kolies a rozchod. Over počet impulzov po prevodovke a znamienka. Vyskúšaj rovný úsek aj otočku o 360°. Sleduj rozdiel medzi vypočítaným a reálnym pohybom. Odometriu publikuj s časovou značkou a realistickou kovarianciou.','Measure actual wheel diameter and track width. Verify counts after the gearbox and direction signs. Test straight travel and a 360° turn. Compare estimated and actual motion. Publish odometry with a timestamp and realistic covariance.')},
 {title:bi('Zjednoť rámce a čas','Unify frames and time'),body:bi('Vytvor reťazec map → odom → base_link → laser. Extrinsickú polohu LiDARu meraj voči podvozku. Over časové značky a spoločný zdroj času. Vizualizácia v RViz musí ukázať sken na správnej strane robota, aj keď sa otáča.','Build the chain map → odom → base_link → laser. Measure the LiDAR extrinsics relative to the chassis. Verify timestamps and a shared time source. In RViz the scan must remain on the correct side of the robot while it turns.')},
 {title:bi('Vytvor a skontroluj mapu','Build and inspect a map'),body:bi('Použi SLAM Toolbox a pohybuj sa pomaly. Urob uzavretú trasu späť na začiatok. Rozdvojené steny často znamenajú chybu času, odometrie alebo kalibrácie. Mapu ulož až po kontrole geometrie. Výučbový LiDAR experiment ti ukáže tieňovanie, nie kompletný SLAM.','Use SLAM Toolbox and move slowly. Complete a loop back to the start. Doubled walls often indicate timing, odometry or calibration errors. Save the map after checking geometry. The educational LiDAR experiment illustrates occlusion, not a complete SLAM system.')},
 {title:bi('Nastav navigáciu a limity','Configure navigation and limits'),body:bi('V Nav2 nastav footprint vrátane prečnievajúcich častí, bezpečnostnú rezervu mapy a limity rýchlosti/zrýchlenia. Začni jedným blízkym cieľom. Controller musí pri zastaranom príkaze rýchlosti zastaviť. Premeraj reakciu na pohyblivú prekážku.','In Nav2 configure the footprint including protrusions, costmap clearance and velocity/acceleration limits. Start with one nearby goal. The controller must stop on stale velocity commands. Measure the response to a moving obstacle.')},
 {title:bi('Over poruchové stavy','Validate failure behaviour'),body:bi('Zaznamenaj rosbag normálneho aj chybového behu. Otestuj stratu LiDARu, oneskorené správy, prerušené riadenie a nízku batériu. Zaznamenaj podmienky, výsledok a čas do zastavenia. Výsledok jednej úspešnej jazdy nestačí na tvrdenie o spoľahlivosti.','Record rosbags of nominal and failure runs. Test LiDAR loss, delayed messages, interrupted control and low battery. Record conditions, outcome and stopping latency. A single successful run does not establish reliability.')}
 ],sources:[{title:'Nav2 · SLAM',url:'https://docs.nav2.org/rolling/tutorials/general_tutorials/navigation2_with_slam/navigation2_with_slam/'},{title:'ROS REP-105 · Coordinate frames',url:'https://www.ros.org/reps/rep-0105.html'},{title:'ros2_control',url:'https://control.ros.org/jazzy/doc/ros2_control/controller_manager/doc/userdoc.html'}]},
 {id:'drone-sim',title:bi('Autopilot pred prvým letom','An autopilot before the first flight'),subtitle:bi('Over letové režimy a chyby v simulácii PX4.','Validate flight modes and failures in PX4 simulation.'),level:bi('Stredne pokročilý','Intermediate'),time:bi('1–2 pracovné večery','1–2 workshop evenings'),lab:'drone',materials:[
 {name:bi('Počítač pre PX4 SITL','Computer for PX4 SITL'),qty:'1',note:bi('Podporovaný systém podľa konkrétneho vydania PX4.','OS supported by your specific PX4 release.')},
 {name:bi('Gazebo + QGroundControl','Gazebo + QGroundControl'),qty:'1',note:bi('Použi kompatibilné verzie podľa dokumentácie.','Use compatible versions from the documentation.')},
 {name:bi('Záznam skúšok','Test log'),qty:'1',note:bi('Scenár, konfigurácia, výsledok a čas reakcie.','Scenario, configuration, outcome and reaction time.')}
 ],steps:[
 {title:bi('Zafixuj verzie prostredia','Pin environment versions'),body:bi('Podľa dokumentácie zvoleného stabilného PX4 nainštaluj podporované vývojové prostredie. Zaznamenaj verziu PX4, Gazebo a QGroundControl. Tento projekt je simulácia na počítači a nepotrebuje fyzický dron.','Follow the selected stable PX4 documentation to install its supported development environment. Record PX4, Gazebo and QGroundControl versions. This computer simulation project does not require a physical drone.')},
 {title:bi('Spusť základný simulovaný model','Launch the default simulated vehicle'),body:bi('Spusť podporovaný SITL model kvadrokoptéry a pripoj QGroundControl. Over telemetriu a odhad polohy. Zmeny parametrov ukladaj spolu s verziou modelu, aby bol pokus opakovateľný.','Launch a supported quadcopter SITL model and connect QGroundControl. Verify telemetry and the position estimate. Save parameter changes with the model version so the experiment can be repeated.')},
 {title:bi('Porovnaj letové režimy','Compare flight modes'),body:bi('V simulácii vykonaj krátky vzlet, visenie a pristátie. Porovnaj riadenie náklonu, výšky a polohy. Zaznamenaj požadovanú aj skutočnú výšku, rýchlosť a stav estimátora. Rozlišuj režim pilota a vnútorné riadiace slučky.','In simulation perform a short takeoff, hover and landing. Compare attitude, altitude and position control. Record commanded and measured altitude, velocity and estimator state. Distinguish pilot modes from inner control loops.')},
 {title:bi('Pridaj hmotnosť a zisti rezervu','Add mass and measure headroom'),body:bi('V interaktívnom modeli zvýš hmotnosť a sleduj potrebný plyn na visenie. Potom podobný pokus zopakuj v dynamickej simulácii. Jednoduchý výpočet ťahu nepredpovedá stabilitu ani výdrž kompletného drona.','Increase mass in the interactive model and observe the required hover throttle. Repeat a comparable experiment in the dynamic simulator. A simple thrust calculation does not predict stability or full-vehicle endurance.')},
 {title:bi('Vyskúšaj stratu riadenia','Test control loss'),body:bi('Nastav reakciu na stratu dátového spojenia, RC a polohy podľa zvoleného scenára. Každý výpadok vyvolaj samostatne v simulácii a over skutočnú zmenu režimu. Reakcia musí zodpovedať prostrediu a dostupnosti odhadu polohy.','Configure data-link, RC and position-loss reactions for the selected scenario. Trigger each failure separately in simulation and verify the actual mode transition. The response must fit the environment and available position estimate.')},
 {title:bi('Vyhodnoť logy a otvorené riziká','Review logs and unresolved risks'),body:bi('Z logov vyhodnoť odchýlku polohy, saturáciu pohonov a čas reakcie failsafe. Prenos do reality vyžaduje samostatné overenie hardvéru, kalibrácie, vrtúľ, batérie a miestnych pravidiel prevádzky. Úspech v SITL nie je letové osvedčenie.','Review position error, actuator saturation and failsafe latency in logs. Moving to hardware requires separate validation of hardware, calibration, propellers, battery and local operating rules. Passing SITL is not flight certification.')}
 ],sources:[{title:'PX4 · Simulation',url:'https://docs.px4.io/main/en/simulation/'},{title:'PX4 · Safety configuration',url:'https://docs.px4.io/v1.17/en/config/safety'}]}
];
