import {simulatePID,lidarScan,batteryEstimate,armPosition,droneEstimate,motorSizing} from './simulations';
export type ChallengeId='pid'|'lidar'|'power'|'kinematics'|'drone'|'motors';
const bi=(sk:string,en:string)=>({sk,en});
type Control={id:string;label:ReturnType<typeof bi>;initial:number;min:number;max:number;step:number;unit:string};
const c=(id:string,sk:string,en:string,initial:number,min:number,max:number,step:number,unit=''):Control=>({id,label:bi(sk,en),initial,min,max,step,unit});
export const challenges={
 pid:{title:bi('Zastav bez rozkývania','Stop without oscillating'),brief:bi('Dostaň prekmit pod 5 % a chybu v celom intervale 6–8 s pod 0,02. Cieľová poloha je 1.','Bring overshoot below 5% and keep error below 0.02 throughout 6–8 s. Target position is 1.'),why:bi('D pôsobí proti rýchlej zmene polohy. Nestačí malý prekmit: robot sa musí aj dostať k cieľu.','D opposes rapid position changes. Low overshoot alone is not enough: the robot must also reach its target.'),controls:[c('p','P · sila opravy','P · correction strength',4,0,20,.1),c('i','I · nahromadená chyba','I · accumulated error',0,0,10,.1),c('d','D · tlmenie','D · damping',.5,0,12,.1)],chapter:'pid'},
 lidar:{title:bi('Pozri sa za prekážku','Look behind the obstacle'),brief:bi('Presuň senzor tak, aby aspoň 5 lúčov zasiahlo prekážku B. Dosah 400 cm, 180 lúčov a nulový šum zostávajú rovnaké.','Move the sensor until at least 5 rays hit obstacle B. Range 400 cm, 180 rays and zero noise stay fixed.'),why:bi('LiDAR meria prvý odraz v danom smere. Nová poloha otvorí lúčom cestu k predtým zakrytému objektu.','LiDAR measures the first return along each direction. A new viewpoint opens paths to a previously occluded object.'),controls:[c('x','Poloha senzora X','Sensor X',120,50,210,1,'cm'),c('y','Poloha senzora Y','Sensor Y',185,50,325,1,'cm')],chapter:'range'},
 power:{title:bi('Vydrž celú hodinu','Last a full hour'),brief:bi('Dosiahni aspoň 60 min pri prúde do 3 A a kapacite do 3,5 Ah. Batéria 11,1 V, účinnosť 90 %, rezerva 20 %, motory 18 W a ostatný príkon 3 W sú pevné. Počítač potrebuje aspoň 6 W.','Reach at least 60 min at no more than 3 A and 3.5 Ah. Fixed: 11.1 V, 90% efficiency, 20% reserve, motors 18 W and other loads 3 W. The computer needs at least 6 W.'),why:bi('Viac Ah pridá energiu. Úspornejší počítač zníži odber. Prúd závisí od príkonu a napätia, nie od samotnej kapacity.','More Ah adds energy. A lower-power computer reduces consumption. Current depends on power and voltage, not capacity alone.'),controls:[c('ah','Kapacita batérie','Battery capacity',3,1,3.5,.1,'Ah'),c('computer','Príkon počítača','Computer power',8,6,15,.1,'W')],chapter:'energy'},
 kinematics:{title:bi('Traf označené miesto','Reach the marked point'),brief:bi('Dostaň koniec ramena na terč: x = 2,05; y = 1,334. Tolerancia je 0,02 modelovej jednotky. Dĺžky článkov sú 1,54 a 1,28; základňa sa neotáča.','Move the endpoint onto the target: x = 2.05; y = 1.334. Tolerance is 0.02 model units. Link lengths are 1.54 and 1.28; the base is fixed.'),why:bi('Poloha konca je súčet pohybov oboch článkov. Uhol lakťa je relatívny k prvému článku.','The endpoint combines both link positions. The elbow angle is relative to the first link.'),controls:[c('a','Ramenný kĺb','Shoulder',62,10,130,1,'°'),c('b','Lakeť','Elbow',-62,-140,90,1,'°')],chapter:'ik'},
 drone:{title:bi('Udrž výšku s nákladom','Maintain altitude with a payload'),brief:bi('Dron 1 kg nesie 0,4 kg nákladu pri náklone 30°. Vyrovnaj zvislé zrýchlenie na ±0,1 m/s² s plynom do 90 %. Každý zo 4 motorov má maximum 5 N.','A 1 kg drone carries 0.4 kg at 30° tilt. Balance vertical acceleration within ±0.1 m/s² at no more than 90% throttle. Each of 4 motors produces up to 5 N.'),why:bi('Zvisle pôsobí T·cos(30°). Vyrovnanie tiaže udrží výšku v tomto modeli, ale dron stále zrýchľuje do strany.','Vertical thrust is T·cos(30°). Balancing weight maintains altitude in this model, but the drone still accelerates sideways.'),controls:[c('throttle','Plyn','Throttle',70,0,90,.1,'%')],chapter:'flight'},
 motors:{title:bi('Vyber prevod pre náklad','Choose gearing for the load'),brief:bi('Udrž 0,5 kg na konci 0,2 m ramena s vlastnou hmotnosťou 0,2 kg. Potrebný moment motora musí byť do 0,1 N·m a výstup aspoň 150 ot/min. Účinnosť 80 %, motor 3 000 ot/min.','Hold 0.5 kg at the end of a 0.2 m arm weighing 0.2 kg. Required motor torque must be at most 0.1 N·m and output speed at least 150 rpm. Efficiency 80%, motor speed 3,000 rpm.'),why:bi('Prevod vymieňa rýchlosť za moment. Preto musíš kontrolovať obe podmienky naraz. Výpočet je statický, bez rozbehového zrýchlenia.','Gearing trades speed for torque, so both requirements must hold together. This is a static calculation without startup acceleration.'),controls:[c('ratio','Redukčný prevod','Gear reduction',10,1,50,1,':1')],chapter:'motors'}
};
export function evaluateChallenge(id:ChallengeId,v:Record<string,number>){if(!challenges[id].controls.every(c=>Number.isFinite(v[c.id])&&v[c.id]>=c.min&&v[c.id]<=c.max))return {passed:false,metrics:[] as {sk:string;en:string;value:string}[]};const metric=(sk:string,en:string,value:string)=>({sk,en,value});switch(id){case 'pid':{const data=simulatePID(v.p,v.i,v.d,1),over=Math.max(0,...data.map(p=>(p.value-1)*100)),tail=Math.max(...data.filter(p=>p.t>=6).map(p=>Math.abs(p.value-1)));return {passed:over<5&&tail<=.02,metrics:[metric('Prekmit','Overshoot',over.toFixed(2)+' %'),metric('Najväčšia chyba 6–8 s','Largest error 6–8 s',tail.toFixed(4))]};}case 'lidar':{const hits=lidarScan(v.x,v.y,400,0,180).filter(p=>p.object===5).length;return {passed:hits>=5,metrics:[metric('Lúče na prekážke B','Rays hitting obstacle B',hits+' / 180')]};}case 'power':{const r=batteryEstimate(11.1,v.ah,21+v.computer,90,20)!;return {passed:!!r&&v.ah<=3.5&&v.computer>=6&&r.hours*60>=60&&r.current<=3,metrics:r?[metric('Výdrž','Runtime',(r.hours*60).toFixed(1)+' min'),metric('Prúd batérie','Battery current',r.current.toFixed(2)+' A')]:[]};}case 'kinematics':{const p=armPosition(v.a,v.b,1.54,1.28),error=Math.hypot(p.x-2.05,p.y-1.333679121828);return {passed:error<=.02,metrics:[metric('Odchýlka od terča','Distance to target',error.toFixed(3)),metric('Poloha x; y','Position x; y',p.x.toFixed(3)+'; '+p.y.toFixed(3))]};}case 'drone':{const r=droneEstimate(1.4,5,v.throttle,30);return {passed:Math.abs(r.acceleration)<=.1&&v.throttle<=90,metrics:[metric('Zvislé zrýchlenie','Vertical acceleration',r.acceleration.toFixed(2)+' m/s²'),metric('Vodorovné zrýchlenie','Horizontal acceleration',r.horizontalAcceleration.toFixed(2)+' m/s²')]};}case 'motors':{const r=motorSizing(.5,.2,.2,v.ratio,80,3000)!;return {passed:r.motorTorque<=.1&&r.outputRpm>=150,metrics:[metric('Potrebný moment motora','Required motor torque',r.motorTorque.toFixed(3)+' N·m'),metric('Výstupné otáčky','Output speed',r.outputRpm.toFixed(0)+' rpm')]};}}}
