import {simulatePID,lidarScan,batteryEstimate,motorSizing} from './simulations';
export type ChallengeId='pid'|'lidar'|'power'|'kinematics'|'drone'|'motors';
export type ParameterChallengeId=Exclude<ChallengeId,'drone'|'kinematics'>;
const bi=(sk:string,en:string)=>({sk,en});
type Control={id:string;label:ReturnType<typeof bi>;initial:number;min:number;max:number;step:number;unit:string};
const c=(id:string,sk:string,en:string,initial:number,min:number,max:number,step:number,unit=''):Control=>({id,label:bi(sk,en),initial,min,max,step,unit});
export const challenges={
 pid:{title:bi('Vylaď odozvu PID','Tune the PID response'),brief:bi('Dostaň prekmit pod 5 % a chybu v celom intervale 6–8 s pod 0,02. Cieľová poloha je 1.','Bring overshoot below 5% and keep error below 0.02 throughout 6–8 s. Target position is 1.'),why:bi('Derivačný člen v tomto modeli tlmí rýchlosť pohybu. Odozva musí súčasne splniť limit prekmitu aj limit polohovej chyby v intervale 6–8 s.','In this model, derivative feedback damps velocity. The response must meet both the overshoot limit and the position-error limit throughout 6–8 s.'),controls:[c('p','P · proporcionálne zosilnenie','P · proportional gain',4,0,20,.1),c('i','I · integračné zosilnenie','I · integral gain',0,0,10,.1),c('d','D · derivačné zosilnenie','D · derivative gain',.5,0,12,.1)],chapter:'pid'},
 lidar:{title:bi('Zmeraj zakrytú prekážku','Measure an occluded obstacle'),brief:bi('Presuň senzor tak, aby aspoň 5 lúčov zasiahlo prekážku B. Dosah 400 cm, 180 lúčov a nulový šum zostávajú rovnaké.','Move the sensor until at least 5 rays hit obstacle B. Range 400 cm, 180 rays and zero noise stay fixed.'),why:bi('LiDAR meria prvý odraz v danom smere. Nová poloha otvorí lúčom cestu k predtým zakrytému objektu.','LiDAR measures the first return along each direction. A new viewpoint opens paths to a previously occluded object.'),controls:[c('x','Poloha senzora X','Sensor X',120,50,210,1,'cm'),c('y','Poloha senzora Y','Sensor Y',185,50,325,1,'cm')],chapter:'range'},
 power:{title:bi('Navrhni napájanie na 60 minút','Design for 60 minutes of runtime'),brief:bi('Dosiahni aspoň 60 min pri prúde do 3 A a kapacite do 3,5 Ah. Batéria 11,1 V, účinnosť 90 %, rezerva 20 %, motory 18 W a ostatný príkon 3 W sú pevné. Počítač potrebuje aspoň 6 W.','Reach at least 60 min at no more than 3 A and 3.5 Ah. Fixed: 11.1 V, 90% efficiency, 20% reserve, motors 18 W and other loads 3 W. The computer needs at least 6 W.'),why:bi('Pri pevnom napätí rastie energia batérie úmerne kapacite. Nižší príkon predlžuje výdrž a znižuje prúd batérie: I = P/(U·η).','At fixed voltage, stored energy is proportional to capacity. Lower power consumption extends runtime and reduces battery current: I = P/(U·η).'),controls:[c('ah','Kapacita batérie','Battery capacity',3,1,3.5,.1,'Ah'),c('computer','Príkon počítača','Computer power',8,6,15,.1,'W')],chapter:'energy'},
 motors:{title:bi('Zvoľ prevod podľa momentu a otáčok','Select gearing for torque and speed'),brief:bi('Udrž 0,5 kg na konci 0,2 m ramena s vlastnou hmotnosťou 0,2 kg. Potrebný moment motora musí byť do 0,1 N·m a výstup aspoň 150 ot/min. Účinnosť 80 %, motor 3 000 ot/min.','Hold 0.5 kg at the end of a 0.2 m arm weighing 0.2 kg. Required motor torque must be at most 0.1 N·m and output speed at least 150 rpm. Efficiency 80%, motor speed 3,000 rpm.'),why:bi('Vyšší redukčný prevod znižuje potrebný moment motora aj výstupné otáčky. Vhodný prevod musí splniť oba limity súčasne. Výpočet nezahŕňa rozbehové zrýchlenie.','A higher reduction ratio lowers both required motor torque and output speed. A suitable ratio must meet both limits. The calculation excludes startup acceleration.'),controls:[c('ratio','Redukčný prevod','Gear reduction',10,1,50,1,':1')],chapter:'motors'}
};
export function evaluateChallenge(id:ParameterChallengeId,v:Record<string,number>){if(!challenges[id].controls.every(c=>Number.isFinite(v[c.id])&&v[c.id]>=c.min&&v[c.id]<=c.max))return {passed:false,metrics:[] as {sk:string;en:string;value:string}[]};const metric=(sk:string,en:string,value:string)=>({sk,en,value});switch(id){case 'pid':{const data=simulatePID(v.p,v.i,v.d,1),over=Math.max(0,...data.map(p=>(p.value-1)*100)),tail=Math.max(...data.filter(p=>p.t>=6).map(p=>Math.abs(p.value-1)));return {passed:over<5&&tail<=.02,metrics:[metric('Prekmit','Overshoot',over.toFixed(2)+' %'),metric('Najväčšia chyba 6–8 s','Largest error 6–8 s',tail.toFixed(4))]};}case 'lidar':{const hits=lidarScan(v.x,v.y,400,0,180).filter(p=>p.object===5).length;return {passed:hits>=5,metrics:[metric('Lúče na prekážke B','Rays hitting obstacle B',hits+' / 180')]};}case 'power':{const r=batteryEstimate(11.1,v.ah,21+v.computer,90,20)!;return {passed:!!r&&v.ah<=3.5&&v.computer>=6&&r.hours*60>=60&&r.current<=3,metrics:r?[metric('Výdrž','Runtime',(r.hours*60).toFixed(1)+' min'),metric('Prúd batérie','Battery current',r.current.toFixed(2)+' A')]:[]};}case 'motors':{const r=motorSizing(.5,.2,.2,v.ratio,80,3000)!;return {passed:r.motorTorque<=.1&&r.outputRpm>=150,metrics:[metric('Potrebný moment motora','Required motor torque',r.motorTorque.toFixed(3)+' N·m'),metric('Výstupné otáčky','Output speed',r.outputRpm.toFixed(0)+' rpm')]};}}}
