import {defaultArena,robotRoute,type Arena,type RobotCommand} from './simulations';
const bi=(sk:string,en:string)=>({sk,en});
const slalom:Arena={start:{x:70,y:100,angle:0},goal:{x:500,y:280},obstacles:[{x:180,y:50,w:90,h:190},{x:350,y:200,w:90,h:140}]};
const code=(steps:[RobotCommand['type'],number][])=>steps.map(([type,value])=>`robot.${type}(${value});`).join('\n');
export const roverMissions=[
 {id:'demo',title:bi('Ukážka riadenia roveru','Rover control demonstration'),brief:bi('Ukážka obsahuje päť príkazov pohybu a otočenia. Šípka označuje smer roveru, prerušovaná čiara prejdenú trasu.','The demonstration contains five movement and turn commands. The arrow marks the rover’s heading; the dashed line marks its path.'),hint:bi('Otočenie +90° je doprava, −90° doľava. Vzdialenosť v príkaze forward je v centimetroch; jeden štvorec mapy má 50 cm.','A +90° turn is right; −90° is left. The forward command uses centimetres; each grid square is 50 cm.'),why:bi('Príkazy forward a turn sa vykonávajú postupne. Otočenie mení smer nasledujúceho pohybu, nie polohu roveru.','Forward and turn commands run sequentially. A turn changes the heading for the next movement without changing the rover’s position.'),arena:defaultArena,starter:code([['forward',130],['turn',-90],['forward',180],['turn',90],['forward',300]]),budget:1000},
 {id:'turn',title:bi('Doplň chýbajúce otočenie','Add the missing turn'),brief:bi('Druhý príkaz zatiaľ neotáča. Uprav jeho uhol tak, aby rover obišiel prekážku zhora a došiel do cieľa.','The second command does not turn yet. Change its angle so the rover passes above the obstacle and reaches the goal.'),hint:bi('Otočenie +90° je doprava, −90° doľava. Príkaz turn(0) smer nezmení.','A +90° turn is right; −90° is left. The command turn(0) leaves the heading unchanged.'),why:bi('Príkaz forward používa aktuálny smer roveru. Každé otočenie sa preto prejaví aj v nasledujúcich úsekoch trasy.','Forward uses the rover’s current heading. Each turn therefore affects the subsequent route segments.'),arena:defaultArena,starter:code([['forward',130],['turn',0],['forward',180],['turn',90],['forward',300]]),budget:1000},
 {id:'repair',title:bi('Nájdi chybu v trase','Find the route error'),brief:bi('Rover sa otáča príliš blízko prekážky. Oprav vzdialenosť v prvom príkaze a otestuj trasu.','The rover turns too close to the obstacle. Fix the distance in the first command and test the route.'),hint:bi('Minimálny odstup stredu roveru od hrany prekážky je v tomto modeli 22 cm. Príkaz turn mení iba smer, nie polohu.','The model requires 22 cm clearance between the rover’s centre and an obstacle edge. A turn changes heading without changing position.'),why:bi('Trasa zachováva odstup od prekážok pre celý podvozok. Pri plánovaní nestačí skontrolovať iba stred robota.','The route leaves obstacle clearance for the whole chassis. Planning must account for the robot’s size, not just its centre.'),arena:defaultArena,starter:code([['forward',180],['turn',-90],['forward',180],['turn',90],['forward',300]]),budget:1000},
 {id:'slalom',title:bi('Naplánuj vlastnú cestu','Plan your own route'),brief:bi('Navrhni trasu zo štartu do cieľa bez kolízie. Cesta medzi prekážkami vedie pod prekážkou 1 a nad prekážkou 2.','Plan a collision-free route from start to goal. The route between the obstacles passes below obstacle 1 and above obstacle 2.'),hint:bi('Otočenie +90° je doprava, −90° doľava. forward(100) znamená pohyb o 100 cm v aktuálnom smere. Jeden štvorec mapy má 50 cm.','A +90° turn is right; −90° is left. forward(100) moves 100 cm along the current heading. Each grid square is 50 cm.'),why:bi('Trasa spĺňa geometrické podmienky simulácie. Pri fyzickom roveri ju treba korigovať podľa meranej polohy, pretože prešmykovanie kolies spôsobuje odchýlku.','The route satisfies the simulation’s geometric constraints. A physical rover needs position feedback to correct errors caused by wheel slip.'),arena:slalom,starter:code([['forward',100]]),budget:1000},
 {id:'efficient',title:bi('Dosiahni cieľ do 10 príkazov','Reach the goal in 10 commands'),brief:bi('Táto trasa dôjde do cieľa, ale používa 16 príkazov. Zjednoduš ju na najviac 10 vykonaných príkazov.','This route reaches the goal but uses 16 commands. Simplify it to at most 10 executed commands.'),hint:bi('Dva po sebe idúce príkazy forward(95) možno spojiť na forward(190). Limit počíta každé vykonané volanie forward, turn a wait, aj vo vnútri cyklu.','Two consecutive forward(95) commands can be combined into forward(190). The limit counts every executed forward, turn and wait call, including calls inside loops.'),why:bi('Trasa dosiahla cieľ v limite vykonaných príkazov. Zlúčenie susedných posunov znižuje počet akcií; zápis do cyklu znižuje iba počet riadkov kódu.','The route reached the goal within the command limit. Combining consecutive movements reduces executed actions; a loop only reduces the number of code lines.'),arena:slalom,starter:code([['turn',90],['forward',95],['forward',95],['wait',1],['turn',-90],['forward',120],['forward',120],['turn',-90],['forward',85],['forward',85],['turn',90],['forward',95],['forward',95],['turn',90],['forward',80],['forward',80]]),budget:10}
];
export function assessMission(index:number,commands:RobotCommand[]){const m=roverMissions[index];const route=robotRoute(commands,m.arena);return {...route,count:commands.length,passed:route.reached&&!route.collision&&commands.length<=m.budget};}
