import {defaultArena,robotRoute,type Arena,type RobotCommand} from './simulations';
const bi=(sk:string,en:string)=>({sk,en});
const slalom:Arena={start:{x:70,y:100,angle:0},goal:{x:500,y:280},obstacles:[{x:180,y:50,w:90,h:190},{x:350,y:200,w:90,h:140}]};
const code=(steps:[RobotCommand['type'],number][])=>steps.map(([type,value])=>`robot.${type}(${value});`).join('\n');
export const roverMissions=[
 {id:'demo',title:bi('Pozri sa, ako rover počúva','See how the rover follows commands'),brief:bi('Spusti krátku ukážku. Šípka ukazuje smer jazdy, prerušovaná čiara už prejdenú trasu.','Run a short demonstration. The arrow shows the heading; the dashed line shows the travelled path.'),hint:bi('Príkazy sa vykonávajú zhora nadol. Záporný uhol otáča doľava.','Commands run from top to bottom. A negative angle turns left.'),why:bi('Rover vykonal pohyb a otočenie v poradí. Teraz doplníš jeden príkaz sám.','The rover moved and turned in sequence. Next you will supply a command yourself.'),arena:defaultArena,starter:code([['forward',130],['turn',-90],['forward',180],['turn',90],['forward',300]]),budget:1000},
 {id:'turn',title:bi('Doplň chýbajúce otočenie','Add the missing turn'),brief:bi('Druhý príkaz zatiaľ neotáča. Uprav jeho uhol tak, aby rover obišiel prekážku zhora a došiel do cieľa.','The second command does not turn yet. Change its angle so the rover passes above the obstacle and reaches the goal.'),hint:bi('Na mape rastie Y nadol. Pravé otočenie je +90°, ľavé −90°.','Y increases down the map. A right turn is +90°; a left turn is −90°.'),why:bi('Otočenie zmenilo smer ďalšieho pohybu. Príkaz forward sa vzťahuje k smeru robota, nie k okraju obrazovky.','The turn changed the direction of the next movement. Forward follows the robot’s heading, not the screen edge.'),arena:defaultArena,starter:code([['forward',130],['turn',0],['forward',180],['turn',90],['forward',300]]),budget:1000},
 {id:'repair',title:bi('Nájdi chybu v trase','Find the route error'),brief:bi('Rover sa otáča príliš blízko prekážky. Oprav vzdialenosť v prvom príkaze a otestuj trasu.','The rover turns too close to the obstacle. Fix the distance in the first command and test the route.'),hint:bi('Robot má šírku. Stred musí zostať aspoň 22 cm od hrany prekážky.','The robot has a width. Its centre must stay at least 22 cm from an obstacle edge.'),why:bi('Kratší prvý úsek vytvoril miesto na otočenie. Nestačí, aby prešiel bod; zmestiť sa musí celý robot.','The shorter first segment created turning clearance. A point fitting through is not enough; the whole robot must fit.'),arena:defaultArena,starter:code([['forward',180],['turn',-90],['forward',180],['turn',90],['forward',300]]),budget:1000},
 {id:'slalom',title:bi('Naplánuj vlastnú cestu','Plan your own route'),brief:bi('Nová mapa, rovnaké príkazy. Obíď prvú prekážku zdola a druhú zhora. Cieľ je vpravo dole.','New map, same commands. Pass below the first obstacle and above the second. The goal is at the bottom right.'),hint:bi('Najprv si nájdi voľné vodorovné koridory. Môžeš pridávať aj odstraňovať príkazy.','Find the clear horizontal corridors first. You can add and remove commands.'),why:bi('Rozdelil si cestu na bezpečné úseky. Na skutočnom robote treba priebežne merať polohu, pretože kolesá môžu prešmyknúť.','You split the route into clear segments. A real robot needs position feedback because its wheels can slip.'),arena:slalom,starter:code([['forward',100]]),budget:1000},
 {id:'efficient',title:bi('Dosiahni cieľ do 10 príkazov','Reach the goal in 10 commands'),brief:bi('Táto trasa dôjde do cieľa, ale používa 16 príkazov. Zjednoduš ju na najviac 10 vykonaných príkazov.','This route reaches the goal but uses 16 commands. Simplify it to at most 10 executed commands.'),hint:bi('Susedné pohyby rovnakým smerom môžeš spojiť. Aj wait sa počíta; cyklus počet vykonaných príkazov nezníži.','Merge consecutive movements in the same direction. Wait also counts; a loop does not reduce executed commands.'),why:bi('Zjednodušil si postup bez zmeny jeho výsledku. Počíta sa počet vykonaných akcií, nie počet riadkov JavaScriptu.','You simplified the procedure without changing its result. We count executed actions, not JavaScript lines.'),arena:slalom,starter:code([['turn',90],['forward',95],['forward',95],['wait',1],['turn',-90],['forward',120],['forward',120],['turn',-90],['forward',85],['forward',85],['turn',90],['forward',95],['forward',95],['turn',90],['forward',80],['forward',80]]),budget:10}
];
export function assessMission(index:number,commands:RobotCommand[]){const m=roverMissions[index];const route=robotRoute(commands,m.arena);return {...route,count:commands.length,passed:route.reached&&!route.collision&&commands.length<=m.budget};}
