'use client';
import {useState} from 'react';
import {ArrowRight,RotateCcw,Check} from 'lucide-react';
import RobotScene from './robot-scene';
import {useJourney} from './journey-context';
import {armTool,armScale,initialArmPose,pickupPoint,dropPoint,liftHeight,distance3,validArmPose,armStepReady,type ArmPose,type ArmStage} from '@/components/robotics-university/lib/arm-transfer';
import type {Lang} from '@/components/robotics-university/lib/atlas-data';

export default function ArmTransfer({lang,onNext}:{lang:Lang;onNext?:(chapter:string)=>void}) {
 const t=(sk:string,en:string)=>lang==='sk'?sk:en;
 const [pose,setPose]=useState<ArmPose>(initialArmPose),[stage,setStage]=useState<ArmStage>(0),[notice,setNotice]=useState(''),[draft,setDraft]=useState<Partial<Record<keyof ArmPose,string>>>({});
 const {mark}=useJourney(),tip=armTool(pose),target=stage<2?pickupPoint:dropPoint,ready=armStepReady(stage,pose),carrying=stage===1||stage===2;
 const labels=[t('Uchop súčiastku','Grip the part'),t('Zdvihni súčiastku','Lift the part'),t('Ulož na pracovisko B','Place at station B')];
 const directions=[t('Nastav uchopovač na oranžovú súčiastku na pracovisku A. Keď bude odchýlka najviac 2 cm, uchop ju tlačidlom pod ovládaním.','Align the gripper with the orange part at station A. At a distance of 2 cm or less, use the button below the controls to grip it.'),t('Zdvihni uchopenú súčiastku o 15 cm nad východiskovú polohu. Zelená výšková značka ukazuje požadovanú úroveň.','Raise the held part 15 cm above its starting position. The green height marker shows the required level.'),t('Otoč základňu k pracovisku B a nastav rameno nad zelený terč. Ulož súčiastku s odchýlkou najviac 2 cm.','Turn the base towards station B and align the arm with the green target. Place the part within 2 cm of its centre.')];
 const change=(key:keyof ArmPose,value:number)=>{const next={...pose,[key]:value};if(!validArmPose(next)){setNotice(t('Uchopovač by sa dostal pod podlahu alebo príliš blízko základne. Najprv uprav druhý kĺb.','The gripper would move below the floor or too close to the base. Adjust the other joint first.'));return;}setPose(next);setNotice('');};
 const advance=()=>{if(!ready){setNotice(stage===1?t('Ešte zdvihni súčiastku na vyznačenú výšku.','Raise the part to the marked height first.'):t('Uprav polohu podľa odchýlky od cieľa. Na uchopenie aj uloženie je tolerancia 2 cm.','Use the distance readout to align the gripper. Gripping and placing both require a distance of 2 cm or less.'));return;}setNotice('');setStage((stage+1) as ArmStage);if(stage===2)mark('challenges','kinematics');};
 const cm=(v:number)=>`${(v*armScale).toFixed(1)} cm`;
 return <section className="challenge arm-transfer" aria-label={t('Prenos súčiastky ramenom','Arm pick and place')}>
  <header className="mission-heading"><div><span className="eyebrow">{t('MANIPULÁCIA V 3D','3D MANIPULATION')}</span><h2>{t('Prenes súčiastku z A do B','Transfer a part from A to B')}</h2><p>{t('Ovládaj tri kĺby robotického ramena. Zápästie udržiava uchopovač zvislo.','Control the three joints of a robotic arm. The wrist keeps the gripper pointing down.')}</p></div></header>
  <ol className="arm-stages" aria-label={t('Postup úlohy','Task stages')}>{labels.map((label,i)=><li key={label} aria-current={i===stage?'step':undefined} className={i<stage?'done':''}><span>{i<stage?<Check size={14}/>:i+1}</span>{label}</li>)}</ol>
  <div className="arm-workspace">
   <div className="arm-scene"><RobotScene kind="arm" explode={0} moving={false} joints={[pose.yaw,pose.shoulder-90,pose.elbow]} lang={lang} armTask={{stage,target,item:carrying?tip:stage===3?dropPoint:pickupPoint,carrying}}/>
    <div className="arm-scene-caption">{t('Potiahni model pre iný uhol pohľadu','Drag to change the viewing angle')}</div>
   </div>
   <div className="arm-panel">
    <div className="arm-instruction" aria-live="polite"><span className="eyebrow">{stage<3?`${stage+1} / 3`:t('HOTOVO','COMPLETE')}</span><h3>{stage<3?labels[stage]:t('Súčiastka je uložená','Part placed')}</h3><p>{stage<3?directions[stage]:t('Prenos si dokončil ovládaním základne, ramena a lakťa. Rovnaký cieľ môže mať viac polôh kĺbov — ich výpočtom sa zaoberá inverzná kinematika.','You completed the transfer using the base, shoulder and elbow. A target can have more than one joint configuration — finding them is the task of inverse kinematics.')}</p></div>
    {stage<3&&<><div className={`arm-live ${ready?'ready':''}`}><span>{stage===1?t('Zostáva zdvihnúť','Remaining lift'):t('Odchýlka od cieľa','Distance to target')}</span><strong>{cm(stage===1?Math.max(0,liftHeight-tip.y):distance3(tip,target))}</strong><small>{stage===1?t('Cieľ: +15 cm nad pracoviskom A','Target: +15 cm above station A'):t('Tolerancia ≤ 2 cm','Tolerance ≤ 2 cm')}</small></div>
    <fieldset className="arm-joints"><legend className="sr-only">{t('Ovládanie kĺbov','Joint controls')}</legend>{([{key:'yaw',sk:'Základňa',en:'Base',min:-65,max:65},{key:'shoulder',sk:'Rameno',en:'Shoulder',min:20,max:115},{key:'elbow',sk:'Lakeť',en:'Elbow',min:-130,max:-10}] as const).map(c=><label key={c.key}><span>{c[lang]}<output>{pose[c.key]}°</output></span><div><input type="range" aria-label={c[lang]} min={c.min} max={c.max} step={1} value={pose[c.key]} onChange={e=>{setDraft(d=>({...d,[c.key]:undefined}));change(c.key,Number(e.target.value));}}/><input type="number" aria-label={t('Uhol: ','Angle: ')+c[lang]} min={c.min} max={c.max} step={1} value={draft[c.key]??pose[c.key]} onChange={e=>{const text=e.target.value;setDraft(d=>({...d,[c.key]:text}));if(text!==''&&Number(text)>=c.min&&Number(text)<=c.max)change(c.key,Number(text));}} onBlur={()=>setDraft(d=>({...d,[c.key]:undefined}))} onKeyDown={e=>{if(e.key==='Enter')e.currentTarget.blur();}}/></div></label>)}</fieldset>
    <button className={`button primary arm-action ${ready?'ready':''}`} onClick={advance}>{stage===0?t('Uchopiť súčiastku','Grip part'):stage===1?t('Pokračovať: presun na B','Continue: transfer to B'):t('Uložiť súčiastku','Place part')}<ArrowRight size={17}/></button>
    <p className="arm-action-help" role="status">{notice||(ready?t('Poloha vyhovuje. Pokračuj tlačidlom vyššie.','Position is within the target. Continue with the button above.'):t('Posuvníky menia polohu okamžite. Čísla umožňujú presné doladenie po 1°.','Sliders move the arm immediately. Use the number fields for precise 1° adjustments.'))}</p></>}
    {stage===3&&onNext&&<button className="button primary arm-action" onClick={()=>onNext('ik')}>{t('Pokračovať: ako robot vypočíta pohyb','Continue: how a robot calculates motion')}<ArrowRight size={17}/></button>}
    <button className="button arm-reset" onClick={()=>{setPose(initialArmPose);setStage(0);setNotice('');setDraft({});}}><RotateCcw size={15}/>{t('Začať prenos znova','Restart transfer')}</button>
   </div>
  </div>
  <details className="arm-technical"><summary>{t('Súradnice, ovládanie a princíp','Coordinates, controls and principle')}</summary><div><p>{t('Základňa otáča celú rovinu ramena. Ramenný kĺb mení uhol prvého článku voči horizontále, lakeť mení uhol druhého voči prvému. Pri zmene jedného kĺbu sa mení výška aj dosah. Zápästie automaticky kompenzuje oba uhly, aby uchopovač smeroval nadol.','The base rotates the arm’s plane. The shoulder sets the first link’s angle from horizontal; the elbow sets the second link relative to the first. Changing either affects both height and reach. The wrist compensates for both angles to keep the gripper pointing down.')}</p><p>{t('Dĺžky článkov: 30,8 cm a 25,6 cm. Ramenná os je 19 cm nad podlahou; stred uchopenia je 18,4 cm od zápästia. Meria sa stred medzi čeľusťami, nie poloha zápästia.','Link lengths: 30.8 cm and 25.6 cm. Shoulder axis: 19 cm above the floor; grip centre: 18.4 cm from the wrist. Measurements refer to the centre between the jaws, not the wrist.')}</p><dl>{[['A',pickupPoint],['B',dropPoint],[t('Uchopovač','Gripper'),tip]].map(([label,p])=>{const q=p as typeof tip;return <div key={label as string}><dt>{label as string}</dt><dd>X {cm(q.x)} · Y {cm(q.y)} · Z {cm(q.z)}</dd></div>;})}</dl><p className="small muted">{t('Y je výška nad podlahou. Úloha overuje polohy a poradie manipulácie; nezahŕňa dynamiku pohonov ani úplnú kontrolu kolízií.','Y is height above the floor. This task checks positions and handling sequence; actuator dynamics and full collision detection are outside its scope.')}</p></div></details>
 </section>;
}
