'use client';
import {lazy,Suspense,useState,useEffect,useRef,type ReactNode} from 'react';
import {Compass,BookOpen,FlaskConical,Wrench,Radio,Search,Globe2,ChevronRight,GraduationCap,MessageCircle} from 'lucide-react';
import {SidebarProvider,Sidebar,SidebarContent,SidebarHeader,SidebarFooter,SidebarMenu,SidebarMenuItem,SidebarMenuButton,SidebarTrigger,useSidebar} from '@/components/robotics-university/components/ui/sidebar';
import {Progress} from '@/components/robotics-university/components/ui/progress';
import {categories,labNames,type Lang,type LabId} from '@/components/robotics-university/lib/atlas-data';
import StartLearning from './start-learning';
import {JourneyProvider,useJourney} from './journey-context';
const Explore=lazy(()=>import('./explore'));
import {Encyclopedia,Article,chapters} from './encyclopedia';
const Labs=lazy(()=>import('./labs')),Builder=lazy(()=>import('./builder')),News=lazy(()=>import('./news'));
const validViews=['start','explore','encyclopedia','labs','builder','news','chapter','support'];
export default function Atlas({initialLang='sk',university=false,renderSupport,renderLessonFeedback}:{initialLang?:Lang;university?:boolean;renderSupport?:(lang:Lang)=>ReactNode;renderLessonFeedback?:(chapterId:string,lang:Lang)=>ReactNode}={} ){return <JourneyProvider><SidebarProvider style={{'--sidebar-width':'15.5rem'} as React.CSSProperties}><AtlasApp initialLang={initialLang} university={university} renderSupport={renderSupport} renderLessonFeedback={renderLessonFeedback}/></SidebarProvider></JourneyProvider>;}
function AtlasApp({initialLang,university,renderSupport,renderLessonFeedback}:{initialLang:Lang;university:boolean;renderSupport?:(lang:Lang)=>ReactNode;renderLessonFeedback?:(chapterId:string,lang:Lang)=>ReactNode}){
 const [lang,setLang]=useState<Lang>(initialLang),[view,setView]=useState('start'),[category,setCategory]=useState('all'),[lab,setLab]=useState<LabId>('code'),[chapter,setChapter]=useState('loop'),[saved,setSaved]=useState<string[]>([]),[completed,setCompleted]=useState<string[]>([]),[ready,setReady]=useState(false),[lastChapter,setLastChapter]=useState<string|null>(null),[labReturn,setLabReturn]=useState({view:'encyclopedia',detail:''});const {setOpenMobile}=useSidebar();const {progress:skills}=useJourney();const skillCount=skills.missions.length+skills.challenges.length;const t=(sk:string,en:string)=>lang==='sk'?sk:en;
 const navigate=(target:string,detail?:string)=>{if(target==='labs'&&stateRef.current.view!=='labs'){const from=stateRef.current;setLabReturn({view:from.view,detail:from.view==='chapter'?from.chapter:from.view==='encyclopedia'?from.category:''});}window.location.hash=target+(detail?'/'+detail:'');setOpenMobile(false);};
 const search=()=>{navigate('encyclopedia');setTimeout(()=>document.getElementById('encyclopedia-search')?.focus(),100);};
 const stateRef=useRef({lang,view,category,lab,chapter,saved,completed});stateRef.current={lang,view,category,lab,chapter,saved,completed};
 useEffect(()=>{
  try{const p=JSON.parse(localStorage.getItem('robotics-atlas-v1')??'{}');if(!university&&(p.lang==='sk'||p.lang==='en'))setLang(p.lang);if(chapters.some(c=>c.id===p.lastChapter))setLastChapter(p.lastChapter);if(Array.isArray(p.saved))setSaved(p.saved.filter((id:unknown)=>chapters.some(c=>c.id===id)));if(Array.isArray(p.completed))setCompleted(p.completed.filter((id:unknown)=>chapters.some(c=>c.id===id)));}catch{}setReady(true);
  const sync=()=>{const [v,d]=window.location.hash.slice(1).split('/');if(v==='main')return;setView(validViews.includes(v)?v:'start');if(v==='encyclopedia')setCategory(categories.some(c=>c.id===d)?d:'all');if(v==='labs')setLab(d in labNames?d as LabId:'code');if(v==='chapter'){const id=chapters.some(c=>c.id===d)?d:'loop';setChapter(id);setLastChapter(id);}window.scrollTo({top:0,behavior:'instant'});};sync();window.addEventListener('hashchange',sync);
  const keys=(e:KeyboardEvent)=>{if(e.key==='/'&&!(e.target instanceof HTMLInputElement)&&!(e.target instanceof HTMLTextAreaElement)){e.preventDefault();search();}};window.addEventListener('keydown',keys);return()=>{window.removeEventListener('hashchange',sync);window.removeEventListener('keydown',keys);};
 },[]);
 useEffect(()=>{document.documentElement.lang=lang;if(ready)try{localStorage.setItem('robotics-atlas-v1',JSON.stringify({lang,saved,completed,lastChapter}));}catch{}},[lang,saved,completed,lastChapter,ready]);
 useEffect(()=>{
  const context=(document as Document&{modelContext?:{registerTool:(tool:unknown,options:unknown)=>Promise<void>|void}}).modelContext;if(!context?.registerTool)return;const lifetime=new AbortController();
  const register=(tool:unknown)=>{try{void Promise.resolve(context.registerTool(tool,{signal:lifetime.signal})).catch(()=>{});}catch{}};
  register({name:'read_robotics_atlas',title:'Read Robotics Atlas state',description:'Read current language, section, saved chapters and learning progress on this device.',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute:()=>({...stateRef.current})});
  register({name:'open_robotics_experiment',title:'Open a robotics experiment',description:'Navigate to a built-in interactive experiment. Does not execute user code or change the simulation parameters.',inputSchema:{type:'object',properties:{experiment:{type:'string',enum:Object.keys(labNames)}},required:['experiment'],additionalProperties:false},annotations:{readOnlyHint:false},execute:async(input:unknown)=>{const value=(input as {experiment?:string})?.experiment;if(!value||!(value in labNames))throw new Error('Unknown experiment');navigate('labs',value);await new Promise(resolve=>setTimeout(resolve,50));return {section:stateRef.current.view,experiment:stateRef.current.lab};}});return()=>lifetime.abort();
 },[]);
 const nav=[{id:'start',icon:GraduationCap,label:t('Začni pokusom','Start experimenting')},{id:'explore',icon:Compass,label:t('Objavovať','Explore')},{id:'encyclopedia',icon:BookOpen,label:t('Encyklopédia','Encyclopedia')},{id:'labs',icon:FlaskConical,label:t('Laboratórium','Laboratory')},{id:'builder',icon:Wrench,label:t('Dielňa buildera',"Builder’s workshop")},{id:'news',icon:Radio,label:t('Aktuality z robotiky','Robotics news')},{id:'support',icon:MessageCircle,label:t('Opýtať sa tímu','Ask the team')}];const current=chapters.find(c=>c.id===chapter)!;
 return <><a href="#main" className="skip-link">{t('Preskočiť na obsah','Skip to content')}</a><Sidebar className="atlas-sidebar"><SidebarHeader><button className="brand" onClick={()=>navigate('start')}><img src="/university-assets/bendalabs-logo-hq.png" alt=""/><span>BendaLabs<span className="brand-sub">{university?t('ROBOTICKÁ UNIVERZITA','ROBOTICS UNIVERSITY'):'ROBOTICS ATLAS'}</span></span></button></SidebarHeader><SidebarContent><div className="side-label">{t('ROBOTICKÁ UNIVERZITA','ROBOTICS UNIVERSITY')}</div><SidebarMenu>{nav.map(n=><SidebarMenuItem key={n.id}><SidebarMenuButton className="nav-item" isActive={view===n.id||(n.id==='encyclopedia'&&view==='chapter')} onClick={()=>navigate(n.id)}><n.icon size={19}/><span>{n.label}</span>{n.id==='labs'&&<span className="nav-count">{Object.keys(labNames).length}</span>}</SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu><div className="side-separator"/><div className="side-label">{t('OBLASTI POZNANIA','FIELDS OF KNOWLEDGE')}</div><SidebarMenu>{categories.map(c=><SidebarMenuItem key={c.id}><SidebarMenuButton className="category-nav" isActive={view==='encyclopedia'&&category===c.id} onClick={()=>navigate('encyclopedia',c.id)}><c.icon size={17}/><span>{c[lang]}</span></SidebarMenuButton></SidebarMenuItem>)}</SidebarMenu></SidebarContent><SidebarFooter><div className="journey"><div className="journey-top"><GraduationCap size={20}/><span>{completed.length?t('Tvoj postup','Your progress'):t('Tvoj postup','Your progress')}</span></div><p>{t('Splnené úlohy a kapitoly s overenou odpoveďou.','Completed tasks and chapters with a correct quiz answer.')}</p><Progress value={skillCount/10*100}/><span className="mint small">{skillCount} / 10 {t('praktických zručností','practical skills')}</span><br/><span className="muted small">{completed.length} / {chapters.length} {t('kapitol overených kvízom','chapters checked by quiz')}</span></div>{university&&<a className="university-home-link" href={lang==='en'?'/en':'/'}>{t('Späť na BendaLabs','Back to BendaLabs')}</a>}<div className="sidebar-bottom"><span>BendaLabs © 2026</span><span>SK / EN</span></div></SidebarFooter></Sidebar>
 <div className="app-content"><header className="topbar"><div className="breadcrumb"><SidebarTrigger className="mobile-menu" aria-label={t('Otvoriť navigáciu','Open navigation')}/><span>{t('Robotika','Robotics')}</span><ChevronRight size={14}/><strong>{view==='chapter'?t('Encyklopédia','Encyclopedia'):nav.find(n=>n.id===view)?.label}</strong></div><div className="top-actions"><button className="search-trigger" onClick={search} aria-label={t('Hľadať v encyklopédii','Search the encyclopedia')}><Search size={17}/><span>{t('Hľadať tému alebo pojem','Search topics or terms')}</span><kbd>/</kbd></button><button className="language" onClick={()=>{if(university)window.location.assign((lang==='sk'?'/en/robotics-university':'/roboticka-univerzita')+window.location.hash);else setLang(lang==='sk'?'en':'sk');}} aria-label={t('Switch to English','Prepnúť do slovenčiny')}><Globe2 size={16}/>{lang.toUpperCase()}</button></div></header>
 <main id="main" className="main"><Suspense fallback={<div className="loading-surface" role="status">{t('Načítavam obsah…','Loading content…')}</div>}>{view==='start'?<StartLearning lang={lang} onNavigate={navigate} onImported={()=>{try{const p=JSON.parse(localStorage.getItem('robotics-atlas-v1')??'{}');setSaved(p.saved??[]);setCompleted(p.completed??[]);setLastChapter(p.lastChapter??null);}catch{}}} support={renderSupport?.(lang)}/>:view==='support'?<section className="support-page">{renderSupport?renderSupport(lang):<><h1>{t('Opýtaj sa tímu BendaLabs','Ask the BendaLabs team')}</h1><p>{t('Pošli nám otázku alebo ukáž svoj projekt.','Send us a question or share your project.')}</p><a className="button primary" href={(lang==='en'?'https://bendalabs.sk/en/robotics-university':'https://bendalabs.sk/roboticka-univerzita')+'#support'}>{t('Otvoriť súkromný formulár','Open the private form')}</a></>}</section>:view==='explore'?<Explore lang={lang} onCategory={id=>navigate('encyclopedia',id)} onLab={id=>navigate('labs',id)} onBuilder={()=>navigate('builder')}/>:view==='encyclopedia'?<Encyclopedia lang={lang} category={category} onCategory={setCategory} onOpen={id=>navigate('chapter',id)} saved={saved} completed={completed} lastChapter={lastChapter}/>:view==='chapter'?<Article key={chapter} feedback={renderLessonFeedback?.(chapter,lang)} chapter={current} lang={lang} onBack={()=>navigate('encyclopedia',current.category)} saved={saved.includes(chapter)} onSave={()=>setSaved(old=>old.includes(chapter)?old.filter(id=>id!==chapter):[...old,chapter])} completed={completed.includes(chapter)} onComplete={()=>setCompleted(old=>old.includes(chapter)?old:[...old,chapter])} onOpen={id=>navigate('chapter',id)}/>:view==='labs'?<><button className="button lab-back" onClick={()=>navigate(labReturn.view,labReturn.detail||undefined)}>{labReturn.view==='start'?t('Späť k mojim pokusom','Back to my experiments'):labReturn.view==='chapter'?t('Späť ku kapitole','Back to the chapter'):labReturn.view==='builder'?t('Späť do dielne buildera','Back to the workshop'):labReturn.view==='explore'?t('Späť na objavovanie','Back to Explore'):t('Späť do encyklopédie','Back to the encyclopedia')}</button><Labs lang={lang} active={lab} onChange={id=>navigate('labs',id)} onNavigate={navigate}/></>:view==='builder'?<Builder lang={lang} onLab={id=>navigate('labs',id)}/>:<News lang={lang}/>}</Suspense></main><footer className="footer"><span>BENDA<span className="mint">LABS</span> / {university?t('ROBOTICKÁ UNIVERZITA','ROBOTICS UNIVERSITY'):'ROBOTICS ATLAS'}</span><span>{t('Simulácie, technické princípy a návody na stavbu.','Simulations, technical principles and build guides.')}</span></footer></div></>;
}
