'use client';
import {useState} from 'react';
import data from '@/components/robotics-university/lib/builder-details.json';
import type {Lang} from '@/components/robotics-university/lib/atlas-data';
export function WorkshopPhoto({lang}:{lang:Lang}){const media=data.authenticMedia[0];return <figure className="workshop-story"><img src={media.src} alt={media.alt[lang]} width="1536" height="2048" loading="lazy"/><figcaption><span className="eyebrow">{lang==='sk'?'Z DIELNE BENDALABS':'FROM THE BENDALABS WORKSHOP'}</span><h3>{lang==='sk'?'Od pokusu k vlastnému robotu.':'From experiment to your own robot.'}</h3><p>{media.caption[lang]}</p><p>{media.context[lang]}</p></figcaption></figure>;}
export function RoverShopping({lang}:{lang:Lang}){const t=(sk:string,en:string)=>lang==='sk'?sk:en,[rate,setRate]=useState(.9);return <section className="build-additions"><h2>{t('Konkrétny nákupný zoznam','Your exact shopping list')}</h2><div className="budget-box"><span className="eyebrow">{t('ORIENTAČNÝ ROZPOČET','PLANNING BUDGET')}</span><output>{(29.3+79.92*rate+50).toFixed(2)}–{(29.3+79.92*rate+90).toFixed(2)} €</output><label>{t('Použitý kurz · EUR za 1 USD','Conversion used · EUR per USD')}<input type="number" min="0.1" max="3" step=".01" value={rate} onChange={e=>{const n=Number(e.target.value);if(Number.isFinite(n))setRate(Math.min(3,Math.max(.1,n)));}}/></label><p>{t('Základný výpočet používa príklad kurzu 0,90. Uprav ho podľa svojho nákupu.','The initial calculation uses an example rate of 0.90. Adjust it for your purchase.')}</p><p>{data.rover.budget.notes[lang]}</p><p>{t('Nezahŕňa: ','Excludes: ')}{data.rover.budget.exclusions[lang]}</p></div><div className="exact-bom">{data.rover.exactBOM.map(p=><div key={p.id}><a target="_blank" rel="noopener noreferrer" href={p.url}>{p.qty} × {p.name[lang]}</a><strong>{p.currency==='USD'?'US$':'€'}{p.price.toFixed(2)} / {p.unit[lang]} · {t('spolu','subtotal')} {p.currency==='USD'?'US$':'€'}{(p.price*p.qty).toFixed(2)}</strong><p>{p.notes[lang]}</p></div>)}</div><p>{data.rover.budget.assemblyNote[lang]}</p><div className="build-supplements">{data.rover.allowances.map(a=><details key={a.id}><summary>{a.name[lang]} · {a.min}–{a.max} €</summary><p>{a.basis[lang]}</p><ul>{a.items.map((item,i)=><li key={i}>{item[lang]}</li>)}</ul></details>)}</div><p><strong>{t('Náradie: ','Tools: ')}</strong>{data.rover.budget.tools[lang]}</p></section>;}
export function Troubleshooting({lang,id}:{lang:Lang;id:string}){const section=id==='rover'?data.rover:id==='ros-rover'?data.ros:data.px4;return <section className="builder-section troubleshooting"><h2>{lang==='sk'?'Keď sa niečo nepodarí':'When something goes wrong'}</h2>{section.troubleshooting.map((p,i)=><details key={i}><summary>{p.symptom[lang]}</summary><p>{p.action[lang]}</p></details>)}</section>;}
export function SoftwareSetup({lang,id}:{lang:Lang;id:string}){const s=id==='ros-rover'?data.ros:data.px4;return <section className="setup-guide"><span className="eyebrow">{s.stack.join(' · ')}</span><h3>{s.title[lang]}</h3>{s.prerequisites.map((p,i)=><p key={i}>{p[lang]}</p>)}<div className="source-list">{s.installationSources.filter(p=>!p.url.includes('raw.githubusercontent')).map(p=><a target="_blank" rel="noopener noreferrer" href={p.url} key={p.url}>{p.title}</a>)}</div>{s.commands.map((step,i)=><div key={step.id}><h4>{i+1}. {step.title[lang]}</h4><span className="tag">{step.shell==='pxh'?'PX4 · pxh>':'Ubuntu · Bash'}</span>{'notes' in step&&step.notes&&<p>{step.notes[lang]}</p>}<pre><code>{step.code}</code></pre></div>)}<h4>{lang==='sk'?'Takto vyzerá správny výsledok':'What a successful result looks like'}</h4><ul>{s.outcomes.map((p,i)=><li key={i}><p>{p[lang]}</p></li>)}</ul><p>{s.scope[lang]}</p></section>;}
export function RoverPinout({lang}:{lang:Lang}){return <section className="setup-guide"><h3>{lang==='sk'?'Zapojenie signálov · Uno R3':'Signal wiring · Uno R3'}</h3><div className="pinout-grid">{data.rover.pinout.map(([signal,pin])=><div key={signal}><span>{signal}</span><strong>{pin}</strong></div>)}</div><p>{lang==='sk'?'Pri správnom zapojení uvidíš v Sériovom monitore pri 115200 baud vzdialenosť v centimetroch. Pri neplatnom meraní sa vypíše −1 a motorové výstupy sa vypnú. Pri prekážke pod 25 cm rover zatáča 450 ms. Najprv to over so zdvihnutými kolesami.':'With correct wiring, Serial Monitor at 115200 baud shows distance in centimetres. An invalid reading prints −1 and disables motor outputs. An obstacle closer than 25 cm makes the rover turn for 450 ms. Verify this with the wheels raised first.'}</p></section>;}
export function supplementText(id:string,lang:Lang){if(id==='rover')return data.rover.exactBOM.map(p=>`${p.qty} x ${p.name[lang]} — ${p.price} ${p.currency} / ${p.unit[lang]}\n${p.notes[lang]}\n${p.url}`).join('\n\n')+'\n\n'+data.rover.budget.notes[lang]+'\n'+data.rover.allowances.map(a=>a.name[lang]+': '+a.items.map(i=>i[lang]).join('; ')).join('\n')+'\n\n'+data.rover.troubleshooting.map(x=>x.symptom[lang]+'\n'+x.action[lang]).join('\n\n');const s=id==='ros-rover'?data.ros:data.px4;return s.stack.join(' / ')+'\n\n'+s.prerequisites.map(p=>p[lang]).join('\n')+'\n\n'+s.commands.map(c=>c.title[lang]+'\n'+('notes' in c&&c.notes?c.notes[lang]+'\n':'')+c.code).join('\n\n')+'\n\n'+s.outcomes.map(x=>x[lang]).join('\n')+'\n\n'+s.troubleshooting.map(x=>x.symptom[lang]+'\n'+x.action[lang]).join('\n\n');}
