'use client';
import {useState} from 'react';
import {CheckCircle2,Circle,Octagon,RotateCw,RotateCcw} from 'lucide-react';
import type {Lang} from '@/components/robotics-university/lib/atlas-data';
import {circuitStep,initialCircuit,motorOutput,type CircuitAction} from '@/components/robotics-university/lib/motor-circuit';

export function CourseParts({lang,independent,disabled,onPassed,onTried}:{lang:Lang;independent:boolean;disabled:boolean;onPassed:()=>void;onTried:()=>void}){
 const t=(sk:string,en:string)=>lang==='sk'?sk:en;
 const [state,setState]=useState(()=>initialCircuit(independent));
 const output=motorOutput(state),moving=output===1||output===-1;
 const change=(action:CircuitAction)=>{const next=circuitStep(state,action,independent);setState(next);onTried();if(next.complete&&!state.complete)onPassed();};
 const status=!state.power?t('Na vstupe VM chýba napájanie. Doska môže posielať príkazy, ale motor nemá zdroj energie.','VM has no power. The board can send commands, but the motor has no energy source.'):!state.ground?t('Chýba spoločná GND dosky a drivera. Riadiaci signál nemá spoločnú referenciu; správanie pohonu nemožno spoľahlivo určiť.','The board and driver have no common GND. The signal has no shared reference; drive behaviour cannot be reliably determined.'):state.command===0?t('STOP: driver nepoháňa motor. Napájanie VM zostáva pripojené — STOP neodpája batériu.','STOP: the driver is not driving the motor. VM remains powered — STOP does not disconnect the battery.'):t('Doska určuje smer. Driver prepína výstupy M1/M2 a energia pre motor prichádza z batérie.','The board sets the direction. The driver switches M1/M2 while the battery supplies motor energy.');
 const steps=[{done:state.power&&state.ground,label:t('Napájanie a spoločná GND','Power and common GND')},{done:state.forward,label:t('Chod v smere A','Run in direction A')},...(independent?[{done:state.reverse,label:t('Chod v smere B','Run in direction B')}]:[]),{done:state.complete,label:t('Zastavenie príkazom STOP','Stop with the STOP command')}];
 return <div className="motor-bench"><div className="motor-bench-visual">
  <div className="motor-legend"><span className="motor-logic">{t('Riadiaci signál','Control signal')}</span><span className="motor-power">{t('Napájanie pohonu','Motor power')}</span><span>GND</span></div>
  <svg viewBox="0 0 740 390" className="motor-circuit" role="img" aria-label={t('Doska riadi driver. Batéria napája driver a jeho výstupy sú pripojené k motoru.','The board controls the driver. The battery powers the driver and its outputs connect to the motor.')}>
   <defs><marker id="motor-signal-arrow" viewBox="0 0 10 10" refX="8" refY="5" markerWidth="5" markerHeight="5" orient="auto"><path d="M0 0L10 5L0 10Z" fill="#b2e2bc"/></marker></defs>
   <rect x="30" y="30" width="170" height="132" rx="12" fill="#173526" stroke="#629073"/><text x="115" y="61" textAnchor="middle">{t('Riadiaca doska','Control board')}</text><text x="115" y="89" className="circuit-secondary" textAnchor="middle">{t('Vlastné napájanie','Separate logic supply')}</text><text x="184" y="118" textAnchor="end" className="circuit-pin">PWM / DIR</text><text x="90" y="146" className="circuit-pin">GND</text>
   <rect x="312" y="70" width="174" height="198" rx="12" fill="#18392a" stroke="#85b693"/><text x="399" y="155" textAnchor="middle">{t('Motorový driver','Motor driver')}</text><text x="399" y="181" textAnchor="middle" className="circuit-secondary">H-bridge</text><text x="326" y="115" className="circuit-pin">IN</text><text x="330" y="228" className="circuit-pin">VM</text><text x="365" y="253" className="circuit-pin">GND</text><text x="473" y="111" textAnchor="end" className="circuit-pin">M1</text><text x="473" y="210" textAnchor="end" className="circuit-pin">M2</text>
   <path d="M200 110H303" fill="none" stroke="#b2e2bc" strokeWidth="3" markerEnd="url(#motor-signal-arrow)"/><text x="256" y="94" textAnchor="middle" className="circuit-pin">{state.command===0?'STOP':`PWM · ${state.command===1?'A':'B'}`}</text>
   <rect x="30" y="204" width="170" height="77" rx="12" fill="#302c1d" stroke="#c5a166"/><text x="115" y="236" textAnchor="middle">{t('Batéria','Battery')}</text><text x="115" y="261" className="circuit-secondary" textAnchor="middle">12 V</text>
   <path d="M200 225H237M277 225H312" stroke="#e5bf7b" strokeWidth="4"/><path d={state.power?'M237 225H277':'M237 225L270 204'} fill="none" stroke="#e5bf7b" strokeWidth="4"/><circle cx="237" cy="225" r="4" fill="#e5bf7b"/><circle cx="277" cy="225" r="4" fill="#e5bf7b"/>
   <path d="M200 260H224V325H390V268" stroke="#839e8c" fill="none" strokeWidth="3"/><text x="238" y="351" className="circuit-pin">{t('− batérie / GND drivera','battery − / driver GND')}</text>
   <path d="M106 162V179H12V325H95M135 325H224" stroke="#839e8c" fill="none" strokeWidth="3"/><path d={state.ground?'M95 325H135':'M95 325L129 307'} stroke="#839e8c" strokeWidth="3"/>
   <path d="M486 105H610V130M486 205H610V230" fill="none" stroke={moving?'#e5bf7b':'#687d70'} strokeWidth="4"/>
   <circle cx="610" cy="180" r="50" fill="#0d2117" stroke={output===null?'#e5bf7b':'#9ec4aa'} strokeWidth="3"/>
   <g className={moving?'motor-shaft spinning':''} style={{animationDirection:output===-1?'reverse':'normal'}}><path d="M610 148V212M578 180H642" stroke="#b2e2bc" strokeWidth="6" strokeLinecap="round"/><circle cx="610" cy="180" r="12" fill="#e5bf7b"/></g>
   <text x="610" y="266" textAnchor="middle">DC motor</text><text x="610" y="294" textAnchor="middle" className="circuit-secondary">{output===null?t('Stav neurčený','State unknown'):moving?t(`Smer ${output===1?'A':'B'}`,`Direction ${output===1?'A':'B'}`):t('Bez pohonu','Not driven')}</text>
  </svg>
  <svg viewBox="0 0 360 355" className="motor-circuit motor-circuit-mobile" role="img" aria-label={t('Schéma riadiacej dosky, batérie, drivera a motora','Control board, battery, driver and motor diagram')}>
   <rect x="15" y="15" width="145" height="75" rx="10" fill="#173526" stroke="#629073"/><text x="87" y="44" textAnchor="middle">{t('Doska','Board')}</text><text x="87" y="70" textAnchor="middle" className="circuit-pin">PWM / DIR</text>
   <rect x="205" y="15" width="145" height="75" rx="10" fill="#302c1d" stroke="#c5a166"/><text x="278" y="44" textAnchor="middle">{t('Batéria','Battery')}</text><text x="278" y="70" textAnchor="middle" className="circuit-pin">12 V</text>
   <rect x="205" y="130" width="145" height="100" rx="10" fill="#18392a" stroke="#85b693"/><text x="278" y="184" textAnchor="middle">Driver</text><text x="219" y="151" className="circuit-pin">IN</text><text x="300" y="151" className="circuit-pin">VM</text><text x="295" y="218" className="circuit-pin">GND</text>
   <path d="M160 51H178V110H234V130" stroke="#b2e2bc" strokeWidth="3" fill="none"/><path d="M310 90V101M310 118V130" stroke="#e5bf7b" strokeWidth="4"/><path d={state.power?'M310 101V118':'M310 101L324 115'} stroke="#e5bf7b" strokeWidth="4"/>
   <path d="M35 90V178M35 211V330H310V230M340 90V311H310" stroke="#839e8c" strokeWidth="3" fill="none"/><path d={state.ground?'M35 178V211':'M35 178L51 204'} stroke="#839e8c" strokeWidth="3"/><text x="46" y="318" className="circuit-pin">GND</text>
   <path d="M205 170H85V205M205 200H145V275H85" stroke={moving?'#e5bf7b':'#687d70'} strokeWidth="3" fill="none"/><text x="153" y="158" className="circuit-pin">M1</text><text x="153" y="217" className="circuit-pin">M2</text>
   <circle cx="85" cy="240" r="35" fill="#0d2117" stroke={output===null?'#e5bf7b':'#9ec4aa'} strokeWidth="3"/><g className={moving?'motor-mobile-shaft spinning':'motor-mobile-shaft'} style={{animationDirection:output===-1?'reverse':'normal'}}><path d="M85 216V264M61 240H109" stroke="#b2e2bc" strokeWidth="5" strokeLinecap="round"/><circle cx="85" cy="240" r="9" fill="#e5bf7b"/></g><text x="85" y="300" textAnchor="middle">DC motor</text>
  </svg>
  <div className="motor-readings"><span>VM<strong>{state.power?'12 V':'0 V'}</strong></span><span>{t('Referencia signálu','Signal reference')}<strong>{state.ground?t('Spoločná GND','Common GND'):t('Nepripojená','Disconnected')}</strong></span><span>{t('Povel dosky','Board command')}<strong>{state.command===0?'STOP':t(`Smer ${state.command===1?'A':'B'}`,`Direction ${state.command===1?'A':'B'}`)}</strong></span></div>
  <p className="motor-diagnosis" role="status">{status}</p>
 </div><div className="motor-bench-controls">
  <h3>{independent?t('Oprav prepojenia','Repair the connections'):t('Vyskúšaj riadenie motora','Test motor control')}</h3>
  {independent&&<div className="motor-connections"><button disabled={disabled||state.command!==0||state.complete} aria-pressed={state.power} onClick={()=>change({type:'power'})}>{state.power?<CheckCircle2 size={18}/>:<Circle size={18}/>}<span>{t('Batéria → VM drivera','Battery → driver VM')}<small>{state.power?t('Pripojené','Connected'):t('Prerušené · pripojiť','Open · connect')}</small></span></button><button disabled={disabled||state.command!==0||state.complete} aria-pressed={state.ground} onClick={()=>change({type:'ground'})}>{state.ground?<CheckCircle2 size={18}/>:<Circle size={18}/>}<span>{t('GND dosky → GND drivera','Board GND → driver GND')}<small>{state.ground?t('Prepojené','Connected'):t('Prerušené · prepojiť','Open · connect')}</small></span></button>{state.command!==0&&!state.complete&&<p>{t('Pred zmenou prepojenia zvoľ STOP.','Select STOP before changing a connection.')}</p>}</div>}
  <p className="motor-command-label">{t('Povel z riadiacej dosky','Command from the control board')}</p>
  <div className="motor-command-buttons">{([{value:1,label:t('Smer A','Direction A'),icon:<RotateCw size={18}/>},{value:0,label:'STOP',icon:<Octagon size={18}/>},{value:-1,label:t('Smer B','Direction B'),icon:<RotateCcw size={18}/>} ] as const).map(command=><button key={command.value} aria-pressed={state.command===command.value} disabled={disabled||state.complete} onClick={()=>change({type:'command',value:command.value})}>{command.icon}{command.label}</button>)}</div>
  <p className="motor-purpose">{t('Doska posiela signál, nie výkon pre motor. Driver používa energiu z batérie a podľa povelu mení polaritu na motore.','The board sends a signal, not motor power. The driver uses battery energy and changes motor polarity according to the command.')}</p>
  <ul className="motor-checks" aria-label={t('Overenie pohonu','Drive verification')}>{steps.map(step=><li key={step.label} className={step.done?'done':''}>{step.done?<CheckCircle2 size={17}/>:<Circle size={17}/>}<span>{step.label}</span></li>)}</ul>
 </div></div>;
}
