'use client';
import {useState} from 'react';
import type {Lang} from '@/components/robotics-university/lib/atlas-data';
export function CourseParts({lang,independent,onChange,onHighlight}:{lang:Lang;independent:boolean;onChange:(valid:boolean)=>void;onHighlight:(id:string)=>void}){
 const t=(sk:string,en:string)=>lang==='sk'?sk:en,[command,setCommand]=useState(independent?'':'driver'),[reading,setReading]=useState(independent?'':'controller');
 const parts=[{id:'battery',name:t('Batéria','Battery'),detail:t('Zdroj energie pre logiku a pohony. Napätia jednotlivých vetiev musia zodpovedať použitým súčiastkam.','Energy source for logic and actuators. Each rail must match the component voltage requirements.')},{id:'controller',name:t('Riadiaca doska','Control board'),detail:t('Spracuje meranie alebo povel používateľa a určí príkaz pre driver.','Processes measurements or user input and produces the driver command.')},{id:'driver',name:t('Motorový driver','Motor driver'),detail:t('Riadi prúd motora podľa signálov dosky. Motor nepatrí priamo na GPIO.','Controls motor current from board signals. Never power a motor directly from GPIO.')},{id:'motor',name:t('Motor a prevod','Motor and gearbox'),detail:t('Mení elektrickú energiu na otáčanie kolesa. Každé zo štyroch kolies má samostatný pohon.','Converts electrical energy into wheel rotation. Each wheel has its own drive.')},{id:'sensor',name:t('Predný senzor','Front sensor'),detail:t('Posiela meranie smerom pred roverom. Prekážku vedľa neho toto meranie nemusí zachytiť.','Reports a measurement in front of the rover. This reading may not detect a side obstacle.')}];
 const [selected,setSelected]=useState('controller');
 return <section className="course-parts"><div className="course-part-tabs">{parts.map(p=><button key={p.id} aria-pressed={selected===p.id} onClick={()=>{setSelected(p.id);onHighlight(p.id);}}>{p.name}</button>)}</div><p>{parts.find(p=>p.id===selected)?.detail}</p><div className="course-signal-map"><div><span className="signal-label">{t('Energia','Power')}</span><span>{t('Batéria','Battery')}</span><b>→</b><span>{t('Driver','Driver')}</span><b>→</b><span>{t('Motor','Motor')}</span></div><div><span className="signal-label">{t('Príkaz','Command')}</span><span>{t('Doska','Board')}</span><b>→</b><select aria-label={t('Kam ide príkaz z dosky','Board command destination')} value={command} onChange={e=>{setCommand(e.target.value);onChange(e.target.value==='driver'&&reading==='controller');}}><option value="">{t('Doplň člen','Choose component')}</option><option value="driver">{t('Driver','Driver')}</option><option value="motor">{t('Motor','Motor')}</option><option value="sensor">{t('Senzor','Sensor')}</option></select><b>→</b><span>{t('Motor','Motor')}</span></div><div><span className="signal-label">{t('Meranie','Reading')}</span><span>{t('Senzor','Sensor')}</span><b>→</b><select aria-label={t('Kam ide meranie zo senzora','Sensor reading destination')} value={reading} onChange={e=>{setReading(e.target.value);onChange(command==='driver'&&e.target.value==='controller');}}><option value="">{t('Doplň člen','Choose component')}</option><option value="controller">{t('Doska','Board')}</option><option value="motor">{t('Motor','Motor')}</option><option value="battery">{t('Batéria','Battery')}</option></select></div></div><p className="course-muted">{t('Funkčná schéma, nie zapojenie pinov. Napájanie dosky a senzora nie je v tejto schéme rozkreslené.','Functional diagram, not pin wiring. Board and sensor supply rails are not detailed here.')}</p></section>;
}
