'use client';
import {createContext,useContext,useEffect,useRef,useState,useCallback,type ReactNode} from 'react';
import {emptyJourney,parseJourney,mergeJourney,type Journey} from '@/components/robotics-university/lib/journey';
import {parseCourse,mergeCourse,courseStorageKey} from '@/components/robotics-university/lib/course-progress';
import type {Lang} from '@/components/robotics-university/lib/atlas-data';
const Context=createContext({progress:emptyJourney,ready:false,mark:(_kind:'missions'|'challenges'|'demo',_id:string)=>{}});
export const useJourney=()=>useContext(Context);
export function JourneyProvider({children}:{children:ReactNode}){const [progress,setProgress]=useState(emptyJourney),[ready,setReady]=useState(false);useEffect(()=>{try{setProgress(parseJourney(JSON.parse(localStorage.getItem('robotics-journey-v2')??'{}')));}catch{}setReady(true);const change=()=>{try{setProgress(parseJourney(JSON.parse(localStorage.getItem('robotics-journey-v2')??'{}')));}catch{}};window.addEventListener('robotics-progress',change);window.addEventListener('storage',change);return()=>{window.removeEventListener('robotics-progress',change);window.removeEventListener('storage',change);};},[]);useEffect(()=>{if(ready)try{localStorage.setItem('robotics-journey-v2',JSON.stringify(progress));}catch{}},[progress,ready]);const mark=useCallback((kind:'missions'|'challenges'|'demo',id:string)=>setProgress(p=>kind==='demo'?{...p,demo:true}:{...p,[kind]:[...new Set([...p[kind],id])]}),[]);return <Context.Provider value={{progress,ready,mark}}>{children}</Context.Provider>;}
export function ProgressTransfer({lang,onImported}:{lang:Lang;onImported:()=>void}){const input=useRef<HTMLInputElement>(null),[status,setStatus]=useState('');const {progress}=useJourney(),t=(sk:string,en:string)=>lang==='sk'?sk:en;
 const exportFile=()=>{try{const payload={format:'bendalabs-learning',version:2,course:parseCourse(JSON.parse(localStorage.getItem(courseStorageKey)??'{}')),journey:progress,build:JSON.parse(localStorage.getItem('robotics-build-v1')??'[]'),atlas:JSON.parse(localStorage.getItem('robotics-atlas-v1')??'{}'),drafts:Object.fromEntries(Array.from({length:5},(_,i)=>[String(i),localStorage.getItem('robotics-mission-v2-'+i)]))};const url=URL.createObjectURL(new Blob([JSON.stringify(payload,null,2)],{type:'application/json'})),a=document.createElement('a');a.href=url;a.download='bendalabs-postup.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);setStatus(t('Zálohu otvor na druhom zariadení cez Načítať postup.','Open this backup on the other device using Import progress.'));}catch{setStatus(t('Zálohu sa nepodarilo vytvoriť.','Could not create the backup.'));}};
 const importFile=async(file:File)=>{try{if(file.size>250000)throw Error();const v=JSON.parse(await file.text());if(v.format!=='bendalabs-learning'||v.version!==2||!v.journey||!v.atlas)throw Error();const existing=JSON.parse(localStorage.getItem('robotics-atlas-v1')??'{}');const ids=['loop','frames','energy','motors','range','states','prototype','flight','vision','timing','odometry','pid','bms','calibration','ros','autopilot','imitation','distribution','ik','fusion','qos','failsafe','vla','validation'];const clean=(x:unknown)=>Array.isArray(x)?x.filter((id:unknown)=>typeof id==='string'&&ids.includes(id)):[];localStorage.setItem('robotics-atlas-v1',JSON.stringify({...existing,saved:[...new Set([...clean(existing.saved),...clean(v.atlas.saved)])],completed:[...new Set([...clean(existing.completed),...clean(v.atlas.completed)])],lastChapter:ids.includes(v.atlas.lastChapter)?v.atlas.lastChapter:existing.lastChapter}));localStorage.setItem('robotics-journey-v2',JSON.stringify(mergeJourney(progress,parseJourney(v.journey))));for(let i=0;i<5;i++){const draft=v.drafts?.[i];if(typeof draft==='string'&&draft.length<=15000&&!localStorage.getItem('robotics-mission-v2-'+i))localStorage.setItem('robotics-mission-v2-'+i,draft);}const buildKeys=Array.from({length:6},(_,i)=>['rover-'+i,'ros-rover-'+i,'drone-sim-'+i]).flat();const oldBuild=JSON.parse(localStorage.getItem('robotics-build-v1')??'[]');const build=[...(Array.isArray(oldBuild)?oldBuild:[]),...(Array.isArray(v.build)?v.build:[])].filter(x=>typeof x==='string'&&buildKeys.includes(x));localStorage.setItem('robotics-build-v1',JSON.stringify([...new Set(build)]));if(v.course){const oldCourse=parseCourse(JSON.parse(localStorage.getItem(courseStorageKey)??'{}'));localStorage.setItem(courseStorageKey,JSON.stringify(mergeCourse(oldCourse,parseCourse(v.course))));window.dispatchEvent(new Event('bendalabs-course-progress'));}window.dispatchEvent(new Event('robotics-progress'));onImported();setStatus(t('Postup bol zlúčený s týmto zariadením. Kód sa nespúšťa automaticky.','Progress was merged with this device. Code is not run automatically.'));}catch{setStatus(t('Tento súbor nie je platná záloha postupu BendaLabs.','This is not a valid BendaLabs progress backup.'));}finally{if(input.current)input.current.value='';}};
 return <section className="progress-transfer"><div><h3>{t('Pokračuj aj na inom zariadení','Continue on another device')}</h3><p>{t('Bez účtu. Ulož si postup do súboru a načítaj ho na mobile alebo počítači. Existujúce úspechy sa zachovajú.','No account needed. Save your progress to a file and import it on your phone or computer. Existing achievements are preserved.')}</p></div><div className="button-row"><button className="button" onClick={exportFile}>{t('Uložiť postup','Export progress')}</button><button className="button" onClick={()=>input.current?.click()}>{t('Načítať postup','Import progress')}</button><input ref={input} type="file" accept="application/json,.json" hidden onChange={e=>{const f=e.target.files?.[0];if(f)void importFile(f);}}/></div><p role="status">{status}</p></section>;
}

