'use client';
import {useEffect,useMemo,useState} from 'react';
import {CheckCircle2} from 'lucide-react';
import {challenges,evaluateChallenge,type ChallengeId,type ParameterChallengeId} from '@/components/robotics-university/lib/challenges';
import {lidarScan,obstacles,simulatePID} from '@/components/robotics-university/lib/simulations';
import type {Lang} from '@/components/robotics-university/lib/atlas-data';
import {useJourney} from './journey-context';
import DroneLanding from './drone-landing';
import ArmTransfer from './arm-transfer';
export default function LabChallenge({id,lang,onNext}:{id:ChallengeId;lang:Lang;onNext?:(id:string)=>void}){return id==='drone'?<DroneLanding lang={lang} onNext={onNext}/>:id==='kinematics'?<ArmTransfer lang={lang} onNext={onNext}/>:<ParameterChallenge id={id} lang={lang} onNext={onNext}/>;}
function ParameterChallenge({id,lang,onNext}:{id:ParameterChallengeId;lang:Lang;onNext?:(id:string)=>void}){const def=challenges[id],t=(sk:string,en:string)=>lang==='sk'?sk:en,{mark,progress}=useJourney();const [values,setValues]=useState<Record<string,number>>(()=>Object.fromEntries(def.controls.map(c=>[c.id,c.initial]))),[edited,setEdited]=useState(false),[checked,setChecked]=useState(false);const result=useMemo(()=>evaluateChallenge(id,values),[id,values]);
 const change=(key:string,value:number)=>{const c=def.controls.find(c=>c.id===key)!;if(!Number.isFinite(value))return;setValues(v=>({...v,[key]:Math.min(c.max,Math.max(c.min,value))}));setEdited(true);setChecked(false);};
 return <section className="challenge" aria-label={t('Praktická výzva','Practical challenge')}><div className="mission-heading"><div><span className="eyebrow">{t('NASTAV · OTESTUJ · VYHODNOŤ','ADJUST · TEST · EVALUATE')}</span><h2>{def.title[lang]}</h2><p>{def.brief[lang]}</p></div>{progress.challenges.includes(id)&&<span className="tag"><CheckCircle2 size={15}/>{t('Vyriešené','Solved')}</span>}</div><div className="challenge-workspace"><div className="challenge-picture"><ChallengePicture id={id} values={values} lang={lang}/><div className="challenge-metrics">{result.metrics.map(m=><div key={m.en}><span>{m[lang]}</span><strong>{m.value}</strong></div>)}</div></div><fieldset className="challenge-controls"><legend>{t('Tvoje nastavenie','Your settings')}</legend>{def.controls.map(c=><label key={c.id}><span>{c.label[lang]} <strong>{values[c.id]} {c.unit}</strong></span><input type="range" aria-label={c.label[lang]} min={c.min} max={c.max} step={c.step} value={values[c.id]} onChange={e=>change(c.id,Number(e.target.value))}/><NumericSetting label={c.label[lang]+t(' · presná hodnota',' · exact value')} min={c.min} max={c.max} step={c.step} value={values[c.id]} onValue={n=>change(c.id,n)}/></label>)}<button className="button primary" disabled={!edited} onClick={()=>{setChecked(true);if(result.passed)mark('challenges',id);}}>{t('Overiť výsledok','Check result')}</button>{!edited&&<p className="small muted">{t('Zmeň aspoň jeden parameter a sleduj výsledok.','Change at least one parameter and observe the result.')}</p>}</fieldset></div>{checked&&<div className="challenge-verdict"><div role="status"><h3>{result.passed?t('Úloha splnená.','Task complete.'):t('Podmienky ešte nie sú splnené.','The requirements are not met yet.')}</h3><p>{result.passed?t('Výsledok je započítaný do tvojich zručností.','Your result has been added to your skills.'):def.brief[lang]}</p></div>{result.passed&&<>{onNext&&<button className="button primary" onClick={()=>onNext(def.chapter)}>{t('Pokračovať k vysvetleniu v kapitole','Continue to the explanation in the chapter')}</button>}<p>{def.why[lang]}</p></>}</div>}</section>;
}
export function ChallengePicture({id,values:v,lang}:{id:ParameterChallengeId;values:Record<string,number>;lang:Lang}){const [time,setTime]=useState(0);useEffect(()=>{if(id!=='pid'||window.matchMedia('(prefers-reduced-motion: reduce)').matches)return;let frame=0,start=performance.now();const tick=(now:number)=>{setTime((Math.max(0,now-start)/1000)%8);frame=requestAnimationFrame(tick);};frame=requestAnimationFrame(tick);return()=>cancelAnimationFrame(frame);},[id,v]);
 const t=(sk:string,en:string)=>lang==='sk'?sk:en;const base={viewBox:'0 0 600 300',role:'img',className:'challenge-svg'};
 if(id==='pid'){const data=simulatePID(v.p,v.i,v.d),sample=data[Math.max(0,Math.min(data.length-1,Math.floor(time*20)))]??data[0],max=Math.max(1.5,...data.map(p=>p.value)),y=(value:number)=>215-value/max*155;return <svg {...base} aria-label={t('Poloha vozíka a graf odozvy PID','Carriage position and PID response graph')}><path d="M50 38H550" stroke="#587865" strokeWidth="5"/><path d="M350 14V65" stroke="#e5c98a" strokeDasharray="4 3"/><rect x={50+sample.value*300-15} y="24" width="30" height="28" rx="4" fill="#b2e2bc"/><text x="350" y="85" textAnchor="middle">{t('Cieľ','Target')} 1</text><path d={`M45 ${y(1)}H555`} stroke="#e5c98a" strokeDasharray="5 4"/><polyline points={data.map(p=>`${45+p.t/8*510},${y(p.value)}`).join(' ')} stroke="#b2e2bc" strokeWidth="2.5" fill="none"/><circle cx={45+time/8*510} cy={y(sample.value)} r="5" fill="#e5c98a"/><path d="M45 115V240H555" stroke="#537460" fill="none"/><text x="45" y="260">0 s</text><text x="530" y="260">8 s</text></svg>;}
 if(id==='lidar'){const scan=lidarScan(v.x,v.y,400,0,180);return <svg viewBox="0 0 600 380" className="challenge-svg" role="img" aria-label={t('Lúče LiDARu a zakrytá prekážka B','LiDAR rays and occluded obstacle B')}><rect x="20" y="20" width="560" height="340" fill="#10251c" stroke="#547661"/>{scan.map((p,i)=><line key={i} x1={v.x} y1={v.y} x2={p.x} y2={p.y} stroke={p.object===5?'#f2cc83':'#75bd962e'}/>)}{obstacles.map((o,i)=><g key={i}><rect x={o.x} y={o.y} width={o.w} height={o.h} fill={i===1?'#715e32':'#354e40'} stroke={i===1?'#f2cc83':'#698675'}/><text x={o.x+o.w/2} y={o.y+o.h/2} textAnchor="middle">{i===0?'A':'B'}</text></g>)}<circle cx={v.x} cy={v.y} r="10" fill="#b2e2bc"/></svg>;}
 if(id==='power'){const result=evaluateChallenge('power',v),r=Number(result.metrics[0]?.value.split(' ')[0]??0);return <svg {...base} aria-label={t('Energetická rezerva a výdrž batérie','Battery energy and runtime')}><rect x="70" y="85" width="430" height="110" rx="14" fill="none" stroke="#b2e2bc" strokeWidth="4"/><rect x="500" y="117" width="22" height="45" rx="4" fill="#b2e2bc"/><rect x="80" y="95" width={Math.min(410,r/90*410)} height="90" rx="7" fill="#497d59"/><path d="M357 75V208" stroke="#e9c786" strokeWidth="2" strokeDasharray="5 4"/><text x="357" y="232" textAnchor="middle">{t('Cieľ 60 min','Goal 60 min')}</text><text x="95" y="148">{r.toFixed(1)} min</text><text x="80" y="52">11.1 V · {v.ah} Ah</text></svg>;}
 return <svg {...base} aria-label={t('Prevod a statické zaťaženie ramena','Gear reduction and static arm load')}><circle cx="125" cy="155" r="50" fill="#203e2c" stroke="#b2e2bc" strokeWidth="5"/><circle cx="70" cy="155" r="18" fill="#51745c" stroke="#d4e9d9" strokeWidth="3"/><path d="M125 155H450" stroke="#b8d9c4" strokeWidth="12"/><rect x="427" y="110" width="46" height="36" fill="#b2e2bc"/><path d="M450 168V230l-6 -10m6 10l6 -10" fill="none" stroke="#e9c786" strokeWidth="3"/><text x="125" y="70" textAnchor="middle">{v.ratio}:1</text><text x="410" y="92">0.5 kg</text><text x="250" y="190">L = 0.2 m</text><text x="270" y="238">{t('Hmotnosť ramena 0,2 kg','Arm mass 0.2 kg')}</text></svg>;
}

function NumericSetting({label,min,max,step,value,onValue}:{label:string;min:number;max:number;step:number;value:number;onValue:(n:number)=>void}){const [draft,setDraft]=useState(String(value));useEffect(()=>setDraft(String(value)),[value]);return <input className="numeric-setting" type="number" aria-label={label} min={min} max={max} step={step} value={draft} onChange={e=>{const text=e.target.value;setDraft(text);const n=Number(text);if(text!==''&&Number.isFinite(n)&&n>=min&&n<=max)onValue(n);}} onBlur={()=>{const n=draft===''?value:Number(draft),clamped=Number.isFinite(n)?Math.min(max,Math.max(min,n)):value;setDraft(String(clamped));if(clamped!==value)onValue(clamped);}}/>;}
