'use client';
import {useEffect,useRef,useState} from 'react';
import {ArrowUp,ArrowDown,ArrowLeft,ArrowRight,RotateCcw,RotateCw,Octagon} from 'lucide-react';
import {zeroVelocity,type Velocity} from '@/components/robotics-university/lib/mecanum';
import type {Lang} from '@/components/robotics-university/lib/atlas-data';
export function ManualControl({lang,speed,onMove,onStop,onRefresh,onStep,stepBusy=false,disabled=false}:{lang:Lang;speed:number;onMove:(v:Velocity)=>void;onStop:(intentional?:boolean)=>void;onRefresh:()=>void;onStep:(v:Velocity)=>void;stepBusy?:boolean;disabled?:boolean}){
 const held=useRef(false),[stepping,setStepping]=useState(false),t=(sk:string,en:string)=>lang==='sk'?sk:en;
 const refs=useRef({onMove,onStop,onRefresh,speed,disabled});refs.current={onMove,onStop,onRefresh,speed,disabled};
 const release=()=>{held.current=false;refs.current.onStop();};
 useEffect(()=>{const velocities=(key:string):Velocity|undefined=>{const s=refs.current.speed;return ({w:{vx:s,vy:0,omega:0},s:{vx:-s,vy:0,omega:0},a:{vx:0,vy:s,omega:0},d:{vx:0,vy:-s,omega:0},q:{vx:0,vy:0,omega:Math.PI/3},e:{vx:0,vy:0,omega:-Math.PI/3}} as Record<string,Velocity>)[key];};
  const down=(e:KeyboardEvent)=>{if(e.target instanceof HTMLInputElement||e.target instanceof HTMLSelectElement||e.target instanceof HTMLTextAreaElement||e.ctrlKey||e.altKey||e.metaKey||e.repeat)return;if(e.key==='Escape'){e.preventDefault();held.current=false;refs.current.onStop(true);return;}const v=velocities(e.key.toLowerCase());if(v&&!refs.current.disabled){e.preventDefault();held.current=true;refs.current.onMove(v);}};
  const up=(e:KeyboardEvent)=>{if(velocities(e.key.toLowerCase()))release();};const hidden=()=>{if(document.hidden)release();};
  const timer=setInterval(()=>{if(held.current)refs.current.onRefresh();},80);window.addEventListener('keydown',down);window.addEventListener('keyup',up);window.addEventListener('blur',release);document.addEventListener('visibilitychange',hidden);return()=>{clearInterval(timer);window.removeEventListener('keydown',down);window.removeEventListener('keyup',up);window.removeEventListener('blur',release);document.removeEventListener('visibilitychange',hidden);refs.current.onMove(zeroVelocity);};
 },[]);
 const controls=[{key:'forward',icon:ArrowUp,label:t('Dopredu','Forward'),v:{vx:speed,vy:0,omega:0}},{key:'left',icon:ArrowLeft,label:t('Doľava bokom','Slide left'),v:{vx:0,vy:speed,omega:0}},{key:'right',icon:ArrowRight,label:t('Doprava bokom','Slide right'),v:{vx:0,vy:-speed,omega:0}},{key:'backward',icon:ArrowDown,label:t('Dozadu','Backward'),v:{vx:-speed,vy:0,omega:0}},{key:'ccw',icon:RotateCcw,label:t('Otočiť doľava','Turn left'),v:{vx:0,vy:0,omega:Math.PI/3}},{key:'cw',icon:RotateCw,label:t('Otočiť doprava','Turn right'),v:{vx:0,vy:0,omega:-Math.PI/3}}];
 return <div><label className="course-check manual-step-mode"><input type="checkbox" checked={stepping} onChange={e=>{release();setStepping(e.target.checked);}}/>{t('Presné kroky: 10 cm / 15°','Precise steps: 10 cm / 15°')}</label><div className="manual-pad">{controls.map(c=><button key={c.key} className={'manual-key '+c.key} disabled={disabled||(stepping&&stepBusy)} onClick={()=>{if(stepping)onStep(c.v);}} onPointerDown={e=>{if(stepping)return;e.preventDefault();e.currentTarget.setPointerCapture(e.pointerId);held.current=true;onMove(c.v);}} onPointerUp={()=>{if(!stepping)release();}} onPointerCancel={release} onLostPointerCapture={()=>{if(held.current)release();}} onKeyDown={e=>{if((e.key===' '||e.key==='Enter')&&!disabled&&!stepping){e.preventDefault();held.current=true;onMove(c.v);}}} onKeyUp={e=>{if((e.key===' '||e.key==='Enter')&&!stepping)release();}} onBlur={()=>{if(held.current)release();}}><c.icon size={21}/><span>{c.label}</span></button>)}<button className="manual-stop" onClick={()=>{held.current=false;onStop(true);}}><Octagon size={21}/>STOP</button></div><p className="course-muted">{stepping?t('Každé kliknutie vykoná jeden krok. STOP preruší aj tento pohyb.','Each click executes one step. STOP also interrupts this movement.'):t('Podrž smer; uvoľnením zastavíš. Klávesnica: W A S D, Q / E otáčanie, Esc STOP.','Hold a direction; release to stop. Keyboard: W A S D, Q / E to turn, Esc to STOP.')}</p></div>;
}

