'use client';
import {useEffect,useRef,useState,type ReactNode} from 'react';
import {Dialog} from 'radix-ui';
import {ArrowRight,ArrowLeft,BookOpen,Play,Octagon,Check,Download,RotateCcw} from 'lucide-react';
import type {Lang} from '@/components/robotics-university/lib/atlas-data';
import {motorStarter,motorFaultProgram,parseMotorProgram,motorAt,motorElectrical,assessMotorRepair,MotorSyntaxError,motorLessonStorage,type MotorWiring,type MotorProgram} from '@/components/robotics-university/lib/motor-lesson';
import MotorLessonDiagram,{MotorWaveform} from './motor-lesson-diagram';

type Log={point:string;value:string};
export default function MotorLesson({lang,feedback,onNavigate}:{lang:Lang;feedback?:ReactNode;onNavigate:(view:string,id?:string)=>void}){
 const t=(sk:string,en:string)=>lang==='sk'?sk:en;
 const [stage,setStage]=useState(0),[reached,setReached]=useState(0),[intro,setIntro]=useState(true),[ready,setReady]=useState(false);
 const [code,setCode]=useState(motorStarter),[practiceCode,setPracticeCode]=useState(motorFaultProgram),[wiring,setWiring]=useState<MotorWiring>({supply:true,vm:true,ground:true});
 const [record,setRecord]=useState<{command:number;ms:number;pulse:number|null}[]>([]),[recordIndex,setRecordIndex]=useState(0),[running,setRunning]=useState(false),[command,setCommand]=useState(0),[line,setLine]=useState(0),[elapsed,setElapsed]=useState(0),[speed,setSpeed]=useState(1);
 const [error,setError]=useState(''),[ran,setRan]=useState(false),[experiment,setExperiment]=useState(false),[done,setDone]=useState(false),[report,setReport]=useState<ReturnType<typeof assessMotorRepair>|null>(null),[logs,setLogs]=useState<Log[]>([]),[meter,setMeter]=useState('vm'),[notes,setNotes]=useState(''),[verifiedCode,setVerifiedCode]=useState(''),[example,setExample]=useState(60);
 const root=useRef<HTMLElement>(null),heading=useRef<HTMLHeadingElement>(null),frame=useRef(0),programRef=useRef<MotorProgram|null>(null),runCode=useRef(''),runStage=useRef(1);
 const diagnostic=stage===2,activeCode=diagnostic?practiceCode:code,displayCommand=stage===0?example:command,electrical=motorElectrical(displayCommand,stage===0?{supply:true,vm:true,ground:true}:wiring);
 useEffect(()=>{try{const d=JSON.parse(localStorage.getItem(motorLessonStorage)??'{}');if(typeof d.code==='string'&&d.code.length<=6000)setCode(d.code);if(typeof d.practiceCode==='string'&&d.practiceCode.length<=6000)setPracticeCode(d.practiceCode);if(typeof d.notes==='string')setNotes(d.notes.slice(0,3000));if(typeof d.verifiedCode==='string'&&d.verifiedCode.length<=6000)setVerifiedCode(d.verifiedCode);if(Array.isArray(d.logs))setLogs(d.logs.filter((l:Log)=>['vm','logic','output'].includes(l?.point)&&typeof l?.value==='string').slice(0,8));setDone(d.done===true);setExperiment(d.experiment===true);const n=Number.isInteger(d.stage)?Math.max(0,Math.min(3,d.stage)):0;setStage(n);setReached(d.done===true?3:Math.min(2,n));if(n===2)setWiring({supply:d.wiring?.supply!==false,vm:d.wiring?.vm===true,ground:true});}catch{}setReady(true);return()=>cancelAnimationFrame(frame.current);},[]);
 useEffect(()=>{if(!ready)return;try{localStorage.setItem(motorLessonStorage,JSON.stringify({code,practiceCode,notes,done,experiment,stage,logs,wiring,verifiedCode}));window.dispatchEvent(new Event('motor-lesson-progress'));}catch{}},[code,practiceCode,notes,done,experiment,stage,logs,wiring,verifiedCode,ready]);
 const halt=()=>{cancelAnimationFrame(frame.current);setRunning(false);setCommand(0);setLine(0);};
 const enter=(next:number)=>{if(next===stage)return;halt();setStage(next);setReached(r=>Math.max(r,next));setError('');setReport(null);setRecord([]);setElapsed(0);setRan(false);if(next===2){setWiring({supply:true,vm:false,ground:true});setLogs([]);}else setWiring({supply:true,vm:true,ground:true});requestAnimationFrame(()=>{root.current?.scrollIntoView({block:'start',behavior:'instant'});heading.current?.focus({preventScroll:true});});};
 const updateCode=(value:string)=>{diagnostic?setPracticeCode(value):setCode(value);setReport(null);setError('');};
 const finish=(program:MotorProgram)=>{
  setRunning(false);setCommand(0);setLine(program.finalLine);setRan(true);setRecord(program.segments.map(s=>({command:s.command,ms:s.ms,pulse:motorElectrical(s.command,wiring).pulse})));setRecordIndex(0);
  if(runStage.current===1){const active=program.segments.filter(s=>s.command!==0);if(active[0]?.command===30&&active.some(s=>s.command===-60))setExperiment(true);}
  else if(runStage.current===2){const result=assessMotorRepair(program,wiring);setReport(result);if(Object.values(result).every(Boolean)){setDone(true);setVerifiedCode(runCode.current);setReached(3);}}
 };
 const start=()=>{
  let program:MotorProgram;try{program=parseMotorProgram(activeCode);}catch(e){const issue=e as MotorSyntaxError;const messages={syntax:t('Použi jeden príkaz na riadok: motor(60);, wait(1000); alebo stop();','Use one command per line: motor(60);, wait(1000); or stop();'),range:t('motor prijíma celé percentá od −100 do −1 alebo od 1 do 100. Na dobeh použi stop().','motor accepts whole percentages from −100 to −1 or 1 to 100. Use stop() for coast.'),duration:t('wait používa 100–10 000 ms. Celý program môže trvať najviac 30 s.','wait accepts 100–10,000 ms. Total program time is limited to 30 s.'),stop:t('Na koniec pridaj stop();, aby program po skúške nenechal motor pod pohonom.','End with stop(); so the test does not leave the motor driven.'),empty:t('Program musí obsahovať pohon a čas čakania, počas ktorého ho pozoruješ.','Include a motor command and a wait duration in which to observe it.')};setError(`${t('Riadok','Line')} ${issue.line}: ${messages[issue.kind]??messages.syntax}`);return;}
  setError('');setReport(null);setRunning(true);setRecord([]);setElapsed(0);setRan(false);programRef.current=program;runCode.current=activeCode;runStage.current=stage;let captured=false;const began=performance.now();const tick=(now:number)=>{const ms=Math.min(program.duration,(now-began)*speed),s=motorAt(program,ms);if(stage===2&&!captured&&s.command!==0){captured=true;const sample=motorElectrical(s.command,wiring);setLogs(l=>[{point:'vm',value:`${sample.vm.toFixed(1)} V · ${t('začiatok chodu','start of run')}`},{point:'logic',value:`${sample.command>0?'AIN1':'AIN2'}: PWM ${Math.abs(sample.command)} % · 1 kHz · HIGH 3,3 V`},...l].slice(0,8));}setElapsed(ms);setCommand(s.command);setLine(s.line);if(ms>=program.duration)finish(program);else frame.current=requestAnimationFrame(tick);};cancelAnimationFrame(frame.current);frame.current=requestAnimationFrame(tick);
 };
 const measure=()=>{
  let value='';if(meter==='vm')value=`${electrical.vm.toFixed(1)} V`;
  if(meter==='logic')value=command===0?'AIN1 LOW · AIN2 LOW':`${command>0?'AIN1':'AIN2'}: PWM ${Math.abs(command)} % · 1 kHz · HIGH 3,3 V`;
  if(meter==='output')value=electrical.state==='unknown'?t('Neurčené · chýba referencia','Indeterminate · missing reference'):electrical.pulse===null?t('Hi-Z · výstup nepoháňa motor','Hi-Z · output is not driving the motor'):`${electrical.pulse>0?'+':''}${electrical.pulse} V ${t('počas pulzu; medzi pulzmi Hi-Z','during ON; Hi-Z between pulses')}`;
  if(meter==='ground')value=wiring.supply?t('Najprv vypni zdroj motora. Kontinuita sa meria bez napájania.','Switch the motor supply off first. Measure continuity with power disconnected.'):wiring.ground?t('Spojené · spoločná referencia','Connected · shared reference'):t('Rozpojené','Open');
  setLogs(l=>[{point:meter,value},...l].slice(0,8));
 };
 const pointNames:Record<string,string>={vm:t('VM voči GND drivera','VM relative to driver GND'),logic:t('AIN1 / AIN2 · logická sonda','AIN1 / AIN2 · logic probe'),output:t('AOUT1 − AOUT2 · priebeh výstupu','AOUT1 − AOUT2 · output waveform')};
 const exportRecord=()=>{const text=[t('BendaLabs · Ako doska riadi motor','BendaLabs · How a board controls a motor'),'',t('Program z úspešnej skúšky','Program from the successful test'),verifiedCode||practiceCode,'',t('Záznam merania','Measurement log'),...logs.map(l=>`${pointNames[l.point]}: ${l.value}`),'',t('Moje poznámky','My notes'),notes,'',t('Simulácia H-mostíka DRV8833. Nie je to hotové zapojenie konkrétneho roveru.','DRV8833 H-bridge simulation. This is not a verified wiring plan for a specific rover.')].join('\n');const url=URL.createObjectURL(new Blob([text],{type:'text/plain;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='BendaLabs-motor.txt';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
 const labels=[t('Pochop zapojenie','Understand the circuit'),t('Uprav program','Edit the program'),t('Nájdi a oprav chybu','Find and repair the fault'),t('Čo vieš použiť','Apply what you learned')];
 if(!ready)return <p role="status">{t('Načítavam lekciu…','Loading lesson…')}</p>;
 return <article className="motor-lesson" ref={root}>
  {intro&&<Dialog.Root open><Dialog.Portal container={typeof document!=='undefined'?document.getElementById('robotics-university'):undefined}><Dialog.Overlay className="course-intro-overlay"/><Dialog.Content className="ml-intro" onInteractOutside={e=>e.preventDefault()}><span className="eyebrow">{t('PRVÁ LEKCIA · POHON ROBOTA','FIRST LESSON · ROBOT DRIVE')}</span><Dialog.Title>{t('Od príkazu k pohybu motora','From a command to motor movement')}</Dialog.Title><Dialog.Description>{t('Riadiaca doska pracuje so signálmi 3,3 V. Motor potrebuje napájanie 6 V a oveľa väčší prúd. V tejto lekcii pochopíš, čo ich prepája, upravíš program a meraním opravíš nefunkčný pohon.','The controller uses 3.3 V signals. The motor needs a 6 V supply and much more current. Learn what connects them, edit a program, and use measurements to repair a faulty drive.')}</Dialog.Description><div className="ml-intro-chain"><span>{t('Program','Program')}<small>{t('určuje povel','sets the command')}</small></span><ArrowRight/><span>Driver<small>{t('prepína energiu','switches power')}</small></span><ArrowRight/><span>{t('Motor','Motor')}<small>{t('mení ju na pohyb','produces movement')}</small></span></div><p>{t('Nepotrebuješ vybavenie ani znalosť kódu. Príkazy aj elektrické pojmy vysvetlíme pri ich použití. Všetky pokusy v tejto lekcii prebiehajú v simulácii.','No hardware or coding experience is required. Commands and electrical terms are explained where they are used. All experiments in this lesson run in simulation.')}</p><Dialog.Close asChild><button className="button primary" onClick={()=>setIntro(false)}>{t('Otvoriť lekciu','Open lesson')}<ArrowRight size={18}/></button></Dialog.Close></Dialog.Content></Dialog.Portal></Dialog.Root>}
  <header className="ml-header"><div><span className="eyebrow">{t('01 / ZÁKLADY POHONU','01 / DRIVE FOUNDATIONS')}</span><h1>{t('Ako doska riadi motor','How a board controls a motor')}</h1><p>{t('Pochop zapojenie. Naprogramuj pohon. Zisti, prečo nefunguje.','Understand the circuit. Program the drive. Find out why it fails.')}</p></div><span className="free-access">{t('Zadarmo · bez registrácie','Free · no sign-up')}</span></header>
  <nav className="ml-stages" aria-label={t('Časti lekcie','Lesson sections')}>{labels.map((label,i)=><button key={i} disabled={i>reached} aria-current={stage===i?'step':undefined} onClick={()=>enter(i)}><span>{i+1}</span>{label}</button>)}</nav>
  <h2 className="ml-section-title" ref={heading} tabIndex={-1}>{labels[stage]}</h2>
  {stage===0?<>
   <div className="ml-problem"><span>{t('PROBLÉM Z PRAXE','THE ENGINEERING PROBLEM')}</span><p>{t('Chceš roztočiť motor jedného kolesa roveru a meniť jeho smer. Samotný program energiu pre motor nedodá. Potrebuješ pochopiť tri odlišné úlohy: rozhodovanie, spínanie výkonu a mechanický pohyb.','You want to drive one rover wheel and reverse its direction. A program alone cannot supply the motor’s energy. Three distinct jobs are involved: deciding, switching power, and producing mechanical movement.')}</p></div>
   <div className="ml-reading-grid"><section><h3>{t('1. Doska rozhoduje, zdroj napája','1. The controller decides; the supply powers')}</h3><p>{t('GPIO je programovateľný vývod dosky. V tejto zostave jeho úroveň 0 V znamená LOW a 3,3 V HIGH. Takýto výstup slúži na riadenie. Nie je náhradou zdroja, ktorý musí dodať prúd vinutiu motora — najmä pri rozbehu alebo zablokovaní hriadeľa.','GPIO is a programmable controller pin. Here, 0 V means LOW and 3.3 V means HIGH. This output is for control. It cannot replace the supply that delivers current to the motor winding, especially during startup or a stall.')}</p><p>{t('Driver je výkonový medzičlánok. Slabým signálom z dosky ovláda spínače, cez ktoré prúdi energia zo samostatného 6 V zdroja do motora. Vypnutý motor preto môže mať stále napájaný driver.','The driver is the power stage. A low-power signal from the controller operates switches that route energy from a separate 6 V source to the motor. A stopped motor can therefore still have a powered driver.')}</p></section><aside className="ml-spec"><span className="eyebrow">{t('ZOSTAVA TEJTO LEKCIE','THIS LESSON’S SETUP')}</span><dl><dt>{t('Riadenie','Control')}</dt><dd>3,3 V GPIO</dd><dt>{t('Motorový zdroj','Motor supply')}</dt><dd>6 V DC</dd><dt>Driver</dt><dd>DRV8833</dd><dt>{t('Pohon','Actuator')}</dt><dd>{t('Kefový DC motor','Brushed DC motor')}</dd></dl><p>{t('Jeden mostík drivera, jeden motor. nSLEEP je v modeli HIGH, takže driver je povolený.','One driver bridge, one motor. nSLEEP is HIGH in this model, enabling the driver.')}</p></aside></div>
   <section className="ml-demonstration"><div className="ml-demo-heading"><div><h3>{t('2. Smer určuje polarita','2. Polarity sets direction')}</h3><p>{t('H-mostík obsahuje štyri spínače. Jedna diagonálna dvojica pripojí motor jednou polaritou; druhá dvojica opačnou. Preklikni stavy a sleduj žltú cestu prúdu.','An H-bridge contains four switches. One diagonal pair applies one polarity to the motor; the other pair reverses it. Switch states and trace the yellow current path.')}</p></div><div className="ml-state-switch">{[[60,t('Smer A','Direction A')],[0,t('Dobeh','Coast')],[-60,t('Smer B','Direction B')]].map(([n,label])=><button key={n} aria-pressed={example===n} onClick={()=>setExample(Number(n))}>{label}</button>)}</div></div><MotorLessonDiagram command={example} wiring={{supply:true,vm:true,ground:true}} lang={lang}/><div className="ml-truth"><span>AIN1 / AIN2</span><span><b>HIGH / LOW</b>{t('Smer A','Direction A')}</span><span><b>LOW / HIGH</b>{t('Smer B','Direction B')}</span><span><b>LOW / LOW</b>{t('Dobeh · Hi-Z','Coast · Hi-Z')}</span></div><p className="ml-detail">{t('HIGH/HIGH pri DRV8833 znamená dynamické brzdenie. V tejto lekcii používame dobeh: výstupy sú vo vysokej impedancii (Hi-Z), takže motor aktívne nepoháňajú. Dobeh nie je okamžité mechanické zastavenie ani odpojenie zdroja.','On the DRV8833, HIGH/HIGH means dynamic braking. Here we use coast: outputs are high impedance (Hi-Z), so they do not actively drive the motor. Coast is neither an instant mechanical stop nor a supply disconnect.')}</p></section>
   <div className="ml-reading-grid"><section><h3>{t('3. PWM mení čas zapnutia','3. PWM changes ON time')}</h3><p>{t('PWM opakuje krátke pulzy. Frekvencia 1 kHz znamená 1000 periód za sekundu, teda jednu periódu každú milisekundu. Strieda 60 % nechá príslušný vstup HIGH počas 0,6 ms a LOW počas 0,4 ms.','PWM repeats short pulses. A frequency of 1 kHz means 1000 periods per second — one each millisecond. At 60% duty, the relevant input is HIGH for 0.6 ms and LOW for 0.4 ms.')}</p><p>{t('Driver počas zapnutého pulzu pripojí na motor napájanie. Medzi pulzmi používa dobeh. Menšia strieda znižuje podiel času aktívneho pohonu; neznamená automaticky rovnaký podiel otáčok. Tie závisia aj od záťaže a vlastností motora.','During an ON pulse the driver applies the supply to the motor. Between pulses it coasts. A lower duty reduces the fraction of time actively driven; it does not guarantee the same fraction of motor speed. Speed also depends on load and motor properties.')}</p></section><MotorWaveform command={example} lang={lang}/></div>
   <section className="ml-reference"><h3>{t('4. Signál potrebuje spoločnú referenciu','4. Signals need a shared reference')}</h3><p>{t('GND dosky a GND drivera musia byť prepojené. Driver potom posudzuje napätie AIN1 a AIN2 voči rovnakej nule ako doska. Bez tohto prepojenia sa správanie nedá spoľahlivo predpovedať — nestačí, že oba prístroje „majú napájanie“.','Controller and driver GND must be connected. The driver then reads AIN1 and AIN2 relative to the same zero as the controller. Without this link behaviour is unreliable — it is insufficient that both devices “have power”.')}</p></section>
   <div className="ml-next"><p>{t('Teraz prepojíš riadky programu s tým, čo sa deje na vstupe a výstupe drivera.','Next, connect program lines to what happens at the driver’s input and output.')}</p><button className="button primary" onClick={()=>enter(1)}>{t('Prejsť k programu','Continue to the program')}<ArrowRight size={18}/></button></div>
  </>:stage===1||stage===2?<>
   <div className="ml-task"><span className="eyebrow">{diagnostic?t('SAMOSTATNÁ DIAGNOSTIKA','INDEPENDENT DIAGNOSIS'):t('RIADENÝ EXPERIMENT','GUIDED EXPERIMENT')}</span><p>{diagnostic?t('Zostava nereaguje a program má chybu smeru. Spusti skúšobný beh: meranie automaticky zaznamená VM aj riadiaci signál. Podľa záznamu odlíš chýbajúce napájanie od chýbajúceho povelu. Oprav zapojenie a program: jeden chod v smere A, dobeh aspoň 300 ms, potom smer B s menšou striedou než pri prvom chode. Na konci uvoľni motor príkazom stop().','The setup does not respond and the program has a direction error. Run a test: measurements automatically capture VM and the control signal. Use the record to distinguish missing power from a missing command. Repair the circuit and program: one run in A, coast for at least 300 ms, then B at a lower duty than the first run. Finish with stop().'):t('Spusti pripravený program a sleduj zvýraznený riadok, polaritu a PWM. Potom zmeň prvých 60 na 30 a program spusti znova. Porovnaj šírku pulzov; napätie počas zapnutia zostane rovnaké.','Run the prepared program and follow the highlighted line, polarity and PWM. Then change the first 60 to 30 and run again. Compare pulse width; the ON-pulse voltage remains the same.')}</p></div>
   {!diagnostic&&<div className="ml-code-guide"><div><code>motor(60);</code><p>{t('Smer A, strieda 60 %. Záporné číslo zvolí smer B; jeho veľkosť určí striedu.','Direction A, 60% duty. A negative number selects B; its magnitude sets duty.')}</p></div><div><code>wait(1200);</code><p>{t('Ponechá posledný povel 1200 ms, teda 1,2 s. wait samo motor nevypína.','Keeps the last command for 1200 ms, or 1.2 s. wait does not switch the motor off.')}</p></div><div><code>stop();</code><p>{t('Oba vstupy nastaví na LOW. Motor prejde do dobehu; napájanie VM zostáva.','Sets both inputs LOW. The motor coasts; VM supply remains present.')}</p></div></div>}
   <div className="ml-workbench"><div className="ml-observation"><MotorLessonDiagram command={command} wiring={wiring} lang={lang}/><div className="ml-live"><span>{t('Čas programu','Program time')}<strong>{(elapsed/1000).toFixed(2)} s</strong></span><span>{t('Povel','Command')}<strong>{command?`${command>0?'+':''}${command} %`:t('Dobeh','Coast')}</strong></span><span>VM<strong>{electrical.vm} V</strong></span></div>{record.length>0&&!running&&<div className="ml-captured"><strong>{t('Záznam posledného behu','Last run record')}</strong><p>{t('Motor už nedostáva pohon. Vyber časť záznamu a v pokoji porovnaj pulzy.','The motor is no longer driven. Select a recorded phase to inspect its pulses.')}</p><div>{record.map((r,i)=><button key={i} aria-pressed={recordIndex===i} onClick={()=>setRecordIndex(i)}>{r.command?`${r.command>0?'+':''}${r.command} %`:t('Dobeh','Coast')} · {r.ms} ms</button>)}</div><span>{t('Napätie počas pulzu','ON-pulse voltage')}: {record[recordIndex]?.pulse===null?'Hi-Z':`${record[recordIndex]?.pulse} V`}</span></div>}<MotorWaveform command={!running&&record.length?record[recordIndex]?.command??0:command} lang={lang}/></div>
    <div className="ml-program"><div className="ml-editor-title"><h3>{t('Program motora','Motor program')}</h3><span>{t('Príkazy simulátora','Simulator commands')}</span></div><div className="ml-editor"><div className="ml-line-numbers" aria-hidden="true">{activeCode.split('\n').map((_,i)=><span key={i} className={line===i+1?'executing':''}>{i+1}</span>)}</div><textarea aria-label={t('Program motora','Motor program')} value={activeCode} onChange={e=>updateCode(e.target.value)} spellCheck={false} autoCapitalize="off" autoCorrect="off" disabled={running} maxLength={6000}/></div><p className="ml-executing" aria-live="polite">{running?t(`Vykonáva sa riadok ${line}: ${activeCode.split('\n')[line-1]??''}`,`Executing line ${line}: ${activeCode.split('\n')[line-1]??''}`):ran?t('Program skončil príkazom stop().','Program ended with stop().'):t('Každý príkaz patrí na samostatný riadok.','Put each command on a separate line.')}</p><div className="ml-run"><button className="button primary" onClick={start} disabled={running||intro}><Play size={18}/>{running?t('Program beží','Running'):t('Spustiť program','Run program')}</button><button className="button course-stop" onClick={halt}><Octagon size={18}/>STOP</button></div><label className="ml-speed">{t('Prehrávanie','Playback')}<select aria-label={t('Rýchlosť prehrávania','Playback speed')} value={speed} disabled={running} onChange={e=>setSpeed(Number(e.target.value))}><option value="1">1×</option><option value="4">4×</option></select><span>{t('Časy v programe sa nemenia.','Program timings stay unchanged.')}</span></label>{error&&<p role="alert" className="ml-error">{error}</p>}
     {diagnostic?<><div className="ml-meter"><h3>{t('Meranie','Measurements')}</h3><label>{t('Merací bod','Test point')}<select value={meter} onChange={e=>setMeter(e.target.value)} aria-label={t('Merací bod','Test point')}>{Object.entries(pointNames).map(([key,name])=><option key={key} value={key}>{name}</option>)}</select></label><button className="button" onClick={measure}>{t('Odmerať a zapísať','Measure and record')}</button><p>{t('Pri každom behu sa VM a prvý aktívny povel zapíšu automaticky. VM má mať 6 V; motor(60) vytvorí PWM na AIN1. Prítomný povel bez VM nepohne motorom.','Each run automatically records VM and its first active command. VM should be 6 V; motor(60) produces PWM on AIN1. A command without VM cannot power the motor.')}</p></div><details className="ml-wiring"><summary>{t('Zapojenie a napájanie','Wiring and power')}</summary><label><input type="checkbox" checked={wiring.supply} onChange={e=>{halt();setWiring(w=>({...w,supply:e.target.checked}));setReport(null);}}/>{t('Zdroj motora zapnutý','Motor supply ON')}</label><label><input type="checkbox" checked={wiring.vm} disabled={wiring.supply} onChange={e=>{setWiring(w=>({...w,vm:e.target.checked}));setReport(null);}}/>{t('Zdroj 6 V → vstup VM','6 V supply → VM input')}</label><p>{t('Pred zmenou spojov vypni zdroj. Príkaz STOP zdroj neodpája.','Turn the supply off before changing connections. STOP does not disconnect power.')}</p></details></>:<details className="ml-code-reference"><summary>{t('Ako sa príkaz prevedie na piny','How a command maps to pins')}</summary><p>{t('motor(+D): PWM so striedou D na AIN1, LOW na AIN2. motor(−D): LOW na AIN1, PWM na AIN2. stop(): oba LOW. Vlastný firmware musí navyše nakonfigurovať piny a perifériu PWM.','motor(+D): D% PWM on AIN1, LOW on AIN2. motor(−D): LOW on AIN1, PWM on AIN2. stop(): both LOW. Physical firmware must also configure pins and the PWM peripheral.')}</p><p>{t('Tento editor podporuje uvedené tri príkazy, nie celý jazyk JavaScript alebo C++.','This editor supports these three commands, not the full JavaScript or C++ language.')}</p><p>{t('Takto vyzerá rovnaké mapovanie v Arduino-ESP32 po nastavení oboch zvolených pinov pomocou ledcAttach(pin, 1000, 8). IN1 a IN2 sú čísla pinov konkrétnej dosky; tu ich zámerne nepredpisujeme.','The same mapping in Arduino-ESP32 follows configuration of both selected pins with ledcAttach(pin, 1000, 8). IN1 and IN2 are pin numbers for the actual board; no board-specific assignment is prescribed here.')}</p><pre className="ml-firmware"><code>{`void motor(int percent) {
  int duty = abs(percent) * 255 / 100;
  ledcWrite(IN1, 0);
  ledcWrite(IN2, 0);
  if (percent > 0) ledcWrite(IN1, duty);
  if (percent < 0) ledcWrite(IN2, duty);
}
void stop() {
  ledcWrite(IN1, 0);
  ledcWrite(IN2, 0);
}`}</code></pre><p>{t('wait(ms) v pokuse zodpovedá blokujúcemu delay(ms). Pri robote, ktorý má súčasne sledovať senzor, treba riadenie času riešiť bez blokovania.','wait(ms) in this experiment corresponds to blocking delay(ms). A robot that must monitor sensors concurrently needs non-blocking timing.')}</p></details>}
    </div></div>
   {diagnostic&&logs.length>0&&<section className="ml-log"><h3>{t('Tvoj záznam meraní','Your measurement record')}</h3><ol>{logs.map((log,i)=><li key={i}><span>{pointNames[log.point]}</span><strong>{log.value}</strong></li>)}</ol></section>}
   {report&&<section className="ml-report" aria-live="polite"><h3>{Object.values(report).every(Boolean)?t('Pohon obnovený. Program spĺňa zadanie.','Drive restored. The program meets the requirement.'):t('Výsledok skúšky','Test result')}</h3>{Object.entries(report).map(([key,passed])=><p key={key} className={passed?'passed':'failed'}><span aria-hidden="true">{passed?'✓':'→'}</span>{({power:passed?t('Napájanie overené: VM má 6 V a signál spoločnú GND.','Power verified: VM is 6 V and signals have common GND.'):t(`Napájanie nevyhovuje: VM = ${electrical.vm} V. Skontroluj zdroj a spoj k vstupu VM.`,`Power check failed: VM = ${electrical.vm} V. Check the supply and the connection to VM.`),forward:passed?t('Prvý chod používa smer A.','The first run uses direction A.'):t('Prvý chod má začať kladným povelom motor(...).','The first run must begin with a positive motor(...) command.'),reverse:passed?t('Program má dva chody: druhý používa smer B.','The program has two runs: the second uses B.'):t('Smer alebo počet chodov nesedí. Potrebné sú dva chody: kladný povel pre A, potom záporný pre B.','Direction or run count does not match. Two runs are required: a positive command for A, then a negative one for B.'),lower:passed?t('Druhý chod má menšiu striedu PWM než prvý.','The second run has lower PWM duty than the first.'):t('Druhý chod nemá menšiu striedu. Porovnaj veľkosti čísel bez znamienka; znamienko určuje iba smer.','The second run does not have lower duty. Compare magnitudes without the sign; the sign only sets direction.'),coast:passed?t('Medzi chodmi je dobeh aspoň 300 ms.','The runs are separated by at least 300 ms of coast.'):t('Medzi chodmi chýba aspoň 300 ms dobehu. Po stop() musí nasledovať wait(300) alebo dlhší čas.','At least 300 ms of coast is missing between runs. Follow stop() with wait(300) or longer.')})[key]}</p>)}</section>}
   <div className="ml-next"><div>{diagnostic?<p>{t('Oprava sa overí po skončení programu. Pri neúspechu uprav konkrétny bod zo záznamu skúšky.','The repair is checked when the program finishes. If it fails, address the specific item in the test record.')}</p>:<p>{experiment?t('Zmena striedy zmenila riadiaci pulz. Smer a 6 V počas zapnutia určuje iná časť reťazca. Teraz rovnaké súvislosti použiješ pri poruche.','Changing duty changes the control pulse. Direction and the 6 V ON voltage belong to other parts of the chain. Now apply those distinctions to a fault.'):t('Spusti pôvodný program. Potom nastav prvý chod na 30 %, druhý ponechaj −60 % a spusti znova. Zmenu uvidíš na pulzoch aj pri zodpovedajúcom riadku programu.','Run the original program. Then set the first run to 30%, keep the second at −60%, and run again. Observe the change in pulses and the corresponding program line.')}</p>}</div><button className="button primary" disabled={running||(diagnostic?!report||!Object.values(report).every(Boolean):!experiment)} onClick={()=>enter(diagnostic?3:2)}>{diagnostic?t('Vyhodnotiť lekciu','Review the lesson'):t('Prejsť na diagnostiku','Continue to diagnosis')}<ArrowRight size={18}/></button></div>
  </>:<>
   <div className="ml-completion"><Check size={25}/><div><h3>{t('Opravil si celý riadiaci reťazec','You repaired the control chain')}</h3><p>{t('Chýbalo napájanie VM, hoci doska vedela vytvoriť riadiaci signál. Po obnovení napájania bolo potrebné opraviť aj druhý smer v programe. Overený výsledok zahŕňa oba smery, menšiu striedu druhého chodu a dobeh.','VM power was missing even though the controller could generate a signal. After restoring power, the program’s second direction also needed repair. The verified result includes both directions, lower duty on the second run, and coast.')}</p></div></div>
   <div className="ml-reading-grid"><section><h3>{t('Čo si prenesieš k reálnemu robotovi','What transfers to a physical robot')}</h3><p>{t('Keď motor nereaguje, oddeľ tri otázky: je na driveri správne napájanie, prichádza platný povel a zodpovedá mu výstup? Takto hľadáš príčinu podľa dôkazov namiesto náhodnej výmeny súčiastok.','When a motor does not respond, separate three questions: is the driver powered correctly, is a valid command arriving, and does the output match it? This locates causes through evidence instead of random component replacement.')}</p><p>{t('Rozumieš aj tomu, čo zatiaľ nevieš zo simulácie vyvodiť: potrebný prúd, teplotu drivera, presné otáčky ani bezpečný čas zmeny smeru konkrétneho zaťaženého motora. Tie treba zmerať a porovnať s limitmi súčiastok.','You also know what this simulation cannot establish: required current, driver temperature, exact speed or a safe reversal interval for a particular loaded motor. Those require measurements against component ratings.')}</p></section><section className="ml-spec"><h3>{t('Pre budúcu stavbu roveru','For the future rover build')}</h3><p>{t('Pri konkrétnom motore overíme menovité napätie, odber pri záťaži aj pri zablokovaní. Podľa nich vyberieme reálny driver, zdroj a vodiče. Až potom určíme presné piny a nahráme firmware pre zvolenú dosku.','For the actual motor we will check rated voltage, loaded current and stall current. These determine the physical driver, supply and wiring. Only then can we assign exact pins and flash firmware for the chosen board.')}</p><p>{t('Schéma tejto lekcie vysvetľuje funkciu. Nie je ešte montážnym návodom pre tvoj konkrétny rover.','This lesson’s circuit explains function. It is not yet an assembly guide for your specific rover.')}</p></section></div>
   <section className="ml-notes"><label htmlFor="motor-notes">{t('Vlastnými slovami: čo bolo pokazené a ktoré meranie to ukázalo?','In your own words: what was faulty, and which measurement showed it?')}</label><p>{t('Poznámka je pre teba a uloží sa v tomto prehliadači. Nie je to ďalšia podmienka pokračovania.','This note is for you and stays in this browser. It is not another progression gate.')}</p><textarea id="motor-notes" value={notes} onChange={e=>setNotes(e.target.value)} maxLength={3000} placeholder={t('VM…, riadiaci signál…, oprava…','VM…, control signal…, repair…')}/><button className="button" onClick={exportRecord}><Download size={17}/>{t('Stiahnuť program a záznam','Download program and record')}</button></section>
   <div className="ml-next"><p>{t('Tu sa prvá lekcia končí. K pokusu aj vysvetleniu sa môžeš kedykoľvek vrátiť.','This completes the first lesson. You can return to the experiment and explanation at any time.')}</p><button className="button" onClick={()=>enter(1)}><RotateCcw size={18}/>{t('Vrátiť sa k experimentu','Return to the experiment')}</button></div>{feedback}
  </>}
  <details className="ml-sources"><summary>{t('Technické podklady a hranice simulácie','Technical sources and simulation limits')}</summary><p>{t('Riadenie H-mostíka vychádza z tabuľky DRV8833: 00 dobeh, 10 smer A, 01 smer B, 11 brzdenie. Menovité napájanie 6 V a logika 3,3 V sú v povolených rozsahoch čipu. Skutočný prúdový limit závisí od puzdra, modulu, teploty a chladenia.','The H-bridge follows the DRV8833 table: 00 coast, 10 A, 01 B, 11 brake. A 6 V motor supply and 3.3 V logic are within chip limits. Actual current limits depend on package, carrier, temperature and cooling.')}</p><p>{t('Model zobrazuje logické stavy a polaritu počas zapnutého pulzu. Otáčanie hriadeľa je názorné, nie výpočet otáčok. Nezahŕňa indukčnosť, spätné elektromotorické napätie, prúdové obmedzenie ani tepelné správanie. Zvolená 300 ms pauza je podmienka pokusu, nie univerzálne bezpečný čas reverzácie.','The model shows logic states and ON-pulse polarity. Shaft rotation is illustrative, not a speed calculation. Inductance, back EMF, current limiting and thermal behaviour are omitted. The 300 ms pause is an exercise condition, not a universally safe reversal delay.')}</p><ul><li><a href="https://www.ti.com/lit/ds/symlink/drv8833.pdf" target="_blank" rel="noreferrer">Texas Instruments · DRV8833 datasheet</a> — {t('napájanie, logické úrovne, tabuľka riadenia a limity','supply, logic thresholds, control table and ratings')}</li><li><a href="https://docs.espressif.com/projects/arduino-esp32/en/latest/api/ledc.html" target="_blank" rel="noreferrer">Espressif · LEDC / PWM</a> — {t('konfigurácia PWM vo firmvéri','PWM configuration in firmware')}</li><li><a href="https://www.pololu.com/product/2130" target="_blank" rel="noreferrer">Pololu · DRV8833 carrier</a> — {t('príklad reálneho modulu; jeho zapojenie a limity patria tomuto modulu','an example carrier; its wiring and limits apply to that carrier')}</li></ul></details>
  <div className="ml-bottom"><button className="text-button" onClick={()=>setIntro(true)}><BookOpen size={16}/>{t('Zadanie lekcie','Lesson brief')}</button><button className="text-button" onClick={()=>onNavigate('support')}>{t('Opýtať sa tímu BendaLabs','Ask the BendaLabs team')}</button>{stage>0&&<button className="text-button" onClick={()=>enter(stage-1)}><ArrowLeft size={16}/>{t('Predchádzajúca časť','Previous section')}</button>}</div>
 </article>;
}
