'use client';
import {useEffect,useRef,useState} from 'react';
import * as THREE from 'three';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import RobotDiagram from './robot-diagram';
import {RoundedBoxGeometry} from 'three/addons/geometries/RoundedBoxGeometry.js';
export type RobotKind='arm'|'drone'|'rover';
type Props={kind:RobotKind;explode:number;moving:boolean;joints?:number[];tilt?:number;selected?:string;onSelect?:(id:string)=>void;lang:'sk'|'en'};
export default function RobotScene(props:Props){
 const mount=useRef<HTMLDivElement>(null),latest=useRef(props);latest.current=props;const [failed,setFailed]=useState(false),[flat,setFlat]=useState(false);
 useEffect(()=>{
  const el=mount.current;if(!el||flat)return;setFailed(false);let disposed=false,frame=0;let renderer:THREE.WebGLRenderer;
  try{renderer=new THREE.WebGLRenderer({alpha:true,antialias:true,powerPreference:'low-power'});}catch{setFailed(true);return;}
  renderer.setPixelRatio(Math.min(window.devicePixelRatio,1.75));renderer.shadowMap.enabled=true;renderer.shadowMap.type=THREE.PCFSoftShadowMap;renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=1.2;el.appendChild(renderer.domElement);
  const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(36,1,.1,60);camera.position.set(5.3,3.8,6.4);
  const controls=new OrbitControls(camera,renderer.domElement);controls.target.set(.35,1.55,0);controls.enableDamping=true;controls.enablePan=false;controls.minDistance=5;controls.maxDistance=14;controls.maxPolarAngle=Math.PI*.49;
  scene.add(new THREE.HemisphereLight(0xc9f9e3,0x11221e,2.7));
  const key=new THREE.DirectionalLight(0xf4fff9,5);key.position.set(3,7,4);key.castShadow=true;key.shadow.mapSize.set(1024,1024);key.shadow.camera.left=-5;key.shadow.camera.right=5;key.shadow.camera.top=7;key.shadow.camera.bottom=-5;key.shadow.normalBias=.03;scene.add(key);
  const rim=new THREE.DirectionalLight(0x7bdbb6,4);rim.position.set(-4,3,-4);scene.add(rim);const fill=new THREE.PointLight(0xd9ecff,30);fill.position.set(4,2,-3);scene.add(fill);
  const mats={shell:new THREE.MeshStandardMaterial({color:0xdde4dc,roughness:.3,metalness:.24}),dark:new THREE.MeshStandardMaterial({color:0x182820,roughness:.43,metalness:.75}),metal:new THREE.MeshStandardMaterial({color:0x73887e,roughness:.23,metalness:.92}),mint:new THREE.MeshStandardMaterial({color:0x81d2a9,roughness:.32,metalness:.35}),black:new THREE.MeshStandardMaterial({color:0x070d0b,roughness:.7}),copper:new THREE.MeshStandardMaterial({color:0xcb8650,roughness:.35,metalness:.85}),led:new THREE.MeshStandardMaterial({color:0xafffd2,emissive:0x56d99c,emissiveIntensity:2})};
  function mesh(g:THREE.BufferGeometry,m:THREE.Material,p:THREE.Object3D,pos:number[],part:string){const obj=new THREE.Mesh(g,m);obj.position.set(pos[0],pos[1],pos[2]);obj.castShadow=true;obj.receiveShadow=true;obj.userData.part=part;p.add(obj);return obj;}
  function box(p:THREE.Object3D,s:number[],pos:number[],m:THREE.Material,id:string,r=.06){return mesh(new RoundedBoxGeometry(s[0],s[1],s[2],3,r),m,p,pos,id);}
  function cyl(p:THREE.Object3D,r:number,h:number,pos:number[],m:THREE.Material,id:string,rx=0){const o=mesh(new THREE.CylinderGeometry(r,r,h,48),m,p,pos,id);o.rotation.x=rx;return o;}
  cyl(scene,2.15,.1,[0,-.06,0],mats.black,'base');const grid=new THREE.GridHelper(14,28,0x294331,0x1c3023);grid.position.y=-.12;scene.add(grid);const ring=mesh(new THREE.TorusGeometry(2.15,.012,8,128),mats.mint,scene,[0,0,0],'base');ring.rotation.x=Math.PI/2;
  const model=new THREE.Group();scene.add(model);const parts:{obj:THREE.Object3D,original:THREE.Vector3,offset:THREE.Vector3}[]=[],motors:THREE.Object3D[]=[];let shoulder:THREE.Group|undefined,elbow:THREE.Group|undefined,wrist:THREE.Group|undefined;
  function separate(obj:THREE.Object3D,offset:number[]){parts.push({obj,original:obj.position.clone(),offset:new THREE.Vector3(offset[0],offset[1],offset[2])});}
  if(props.kind==='arm'){
   cyl(model,.87,.15,[0,.09,0],mats.dark,'base');for(let i=0;i<8;i++)cyl(model,.035,.026,[Math.cos(i/4*Math.PI)*.7,.18,Math.sin(i/4*Math.PI)*.7],mats.metal,'base');
   cyl(model,.63,.35,[0,.31,0],mats.metal,'base');cyl(model,.64,.09,[0,.53,0],mats.mint,'base');const cover=cyl(model,.66,.28,[0,.7,0],mats.shell,'base');separate(cover,[0,.5,0]);cyl(model,.39,.48,[0,.82,0],mats.copper,'actuator');
   shoulder=new THREE.Group();shoulder.position.y=.95;model.add(shoulder);cyl(shoulder,.41,.65,[0,0,0],mats.dark,'actuator',Math.PI/2);cyl(shoulder,.35,.07,[0,0,.38],mats.metal,'actuator',Math.PI/2);cyl(shoulder,.21,.08,[0,0,.43],mats.mint,'actuator',Math.PI/2);
   box(shoulder,[.22,1.58,.23],[0,.77,0],mats.metal,'actuator');const upper=box(shoulder,[.56,1.46,.48],[0,.76,0],mats.shell,'links',.15);separate(upper,[.8,0,0]);box(shoulder,[.59,.13,.5],[0,.29,0],mats.mint,'links');for(let i=0;i<5;i++)box(shoulder,[.2,.026,.026],[0,.53+i*.09,.25],mats.dark,'links',.005);
   elbow=new THREE.Group();elbow.position.y=1.54;shoulder.add(elbow);cyl(elbow,.36,.66,[0,0,0],mats.dark,'actuator',Math.PI/2);cyl(elbow,.29,.08,[0,0,.37],mats.shell,'actuator',Math.PI/2);cyl(elbow,.15,.09,[0,0,.42],mats.mint,'actuator',Math.PI/2);
   box(elbow,[.17,1.23,.21],[0,.61,0],mats.metal,'links');const fore=box(elbow,[.43,1.2,.42],[0,.62,0],mats.shell,'links',.12);separate(fore,[-.65,0,0]);box(elbow,[.32,.36,.035],[0,.5,.23],mats.dark,'sensors');box(elbow,[.045,.17,.045],[0,.51,.26],mats.led,'sensors');
   wrist=new THREE.Group();wrist.position.y=1.28;elbow.add(wrist);cyl(wrist,.27,.33,[0,.12,0],mats.dark,'gripper');cyl(wrist,.28,.08,[0,.32,0],mats.mint,'gripper');box(wrist,[.65,.25,.36],[0,.49,0],mats.metal,'gripper');for(const s of [-1,1]){const jaw=box(wrist,[.12,.46,.27],[s*.25,.77,0],mats.dark,'gripper');separate(jaw,[s*.35,0,0]);box(wrist,[.15,.15,.28],[s*.2,1,0],mats.black,'gripper');}
   const wire=new THREE.CatmullRomCurve3([new THREE.Vector3(-.3,.7,-.35),new THREE.Vector3(-.6,1.1,-.35),new THREE.Vector3(-.65,1.9,-.35),new THREE.Vector3(-.3,2.2,-.35)]);mesh(new THREE.TubeGeometry(wire,32,.045,8,false),mats.black,model,[0,0,0],'power');
  }else if(props.kind==='drone'){
   controls.target.set(0,.8,0);camera.position.set(6,5,6);box(model,[1.05,.3,1.45],[0,.82,0],mats.dark,'base');const cover=box(model,[.94,.26,1.3],[0,1.08,0],mats.shell,'links');separate(cover,[0,1.1,0]);const battery=box(model,[.53,.32,.85],[0,1.32,0],mats.mint,'power');separate(battery,[0,1.8,0]);box(battery,[.17,.34,.86],[0,0,0],mats.black,'power');const board=box(model,[.65,.04,.7],[0,1.01,0],mats.mint,'sensors');separate(board,[0,.65,0]);for(let j=0;j<4;j++)box(board,[.1,.06,.12],[(j%2-.5)*.3,.04,Math.floor(j/2)*.25-.13],mats.black,'sensors');
   for(let i=0;i<4;i++){const a=Math.PI/4+i*Math.PI/2,x=Math.cos(a)*1.7,z=Math.sin(a)*1.7;const arm=box(model,[.2,.18,2.1],[x/2,.77,z/2],mats.metal,'links');arm.rotation.y=Math.PI/2-a;cyl(model,.24,.3,[x,.93,z],mats.dark,'actuator');cyl(model,.19,.06,[x,1.1,z],mats.copper,'actuator');const motor=new THREE.Group();motor.position.set(x,1.16,z);model.add(motor);motors.push(motor);box(motor,[1.35,.035,.16],[0,0,0],i%2?mats.mint:mats.shell,'gripper',.055);cyl(motor,.08,.11,[0,.055,0],mats.metal,'gripper');box(model,[.1,.53,.1],[x*.63,.47,z*.63],mats.dark,'base');}
   const cam=box(model,[.36,.3,.3],[0,.66,.83],mats.dark,'sensors');cyl(cam,.11,.06,[0,0,.18],mats.mint,'sensors',Math.PI/2);
  }else{
   camera.position.set(6,4.7,6);controls.target.set(0,1,0);box(model,[1.7,.32,2.05],[0,.61,0],mats.dark,'base');const top=box(model,[1.6,.23,1.92],[0,1.07,0],mats.shell,'links');separate(top,[0,1.4,0]);const battery=box(model,[.6,.3,.9],[.2,.85,-.25],mats.mint,'power');separate(battery,[.7,.6,0]);const board=box(model,[.55,.07,.6],[-.36,.86,.4],mats.mint,'sensors');separate(board,[-.7,.65,0]);box(board,[.2,.07,.23],[0,.07,0],mats.dark,'sensors');
   for(const x of [-1,1])for(const z of [-.69,.69]){cyl(model,.45,.3,[x,.47,z],mats.black,'actuator').rotation.z=Math.PI/2;cyl(model,.24,.31,[x,.47,z],mats.metal,'actuator').rotation.z=Math.PI/2;for(let j=0;j<14;j++){const a=j/14*Math.PI*2,o=box(model,[.32,.045,.12],[x,.47+Math.sin(a)*.445,z+Math.cos(a)*.445],mats.dark,'actuator',.01);o.rotation.x=-a;}}
   cyl(model,.33,.22,[0,1.3,0],mats.dark,'sensors');const lidar=cyl(model,.3,.12,[0,1.49,0],mats.mint,'sensors');separate(lidar,[0,2,0]);for(const x of [-.34,.34])cyl(model,.115,.11,[x,1.01,1.02],mats.metal,'sensors',Math.PI/2);
  }
  const ray=new THREE.Raycaster(),pointer=new THREE.Vector2();let dx=0,dy=0;const down=(e:PointerEvent)=>{dx=e.clientX;dy=e.clientY;};const click=(e:PointerEvent)=>{if(Math.hypot(e.clientX-dx,e.clientY-dy)>6)return;const b=el.getBoundingClientRect();pointer.set((e.clientX-b.left)/b.width*2-1,-(e.clientY-b.top)/b.height*2+1);ray.setFromCamera(pointer,camera);const hit=ray.intersectObject(model,true)[0];if(hit?.object.userData.part)latest.current.onSelect?.(hit.object.userData.part);};renderer.domElement.addEventListener('pointerdown',down);renderer.domElement.addEventListener('pointerup',click);
  const resize=()=>{renderer.setSize(el.clientWidth,el.clientHeight,false);camera.aspect=el.clientWidth/el.clientHeight;camera.updateProjectionMatrix();};const obs=new ResizeObserver(resize);obs.observe(el);resize();
  const start=performance.now();let last='';const originals=new Map<THREE.Mesh,THREE.Material|THREE.Material[]>(),highlight=new THREE.MeshStandardMaterial({color:0xa1efbf,metalness:.45,roughness:.32,emissive:0x2a6648,emissiveIntensity:.3});
  let visible=true;const visibility=new IntersectionObserver(entries=>{visible=entries[0]?.isIntersecting??false;});visibility.observe(el);const lost=(event:Event)=>{event.preventDefault();cancelAnimationFrame(frame);setFailed(true);};renderer.domElement.addEventListener('webglcontextlost',lost);const animate=()=>{if(disposed)return;if(!visible||document.hidden){frame=requestAnimationFrame(animate);return;}const p=latest.current,t=(performance.now()-start)/1000;parts.forEach(({obj,original,offset})=>obj.position.copy(original).addScaledVector(offset,p.explode/100));if(shoulder&&elbow&&wrist){model.rotation.y=(p.joints?.[0]??-18)*Math.PI/180+(p.moving?Math.sin(t*.35)*.25:0);shoulder.rotation.z=(p.joints?.[1]??-28)*Math.PI/180+(p.moving?Math.sin(t*.6)*.08:0);elbow.rotation.z=(p.joints?.[2]??-62)*Math.PI/180+(p.moving?Math.sin(t*.6+1)*.14:0);wrist.rotation.z=.6;}if(p.kind==='drone'){model.rotation.z=-(p.tilt??0)*Math.PI/180;motors.forEach((m,i)=>m.rotation.y=p.moving?t*22*(i%2?1:-1):i*.7);model.position.y=p.moving?.06*Math.sin(t*1.4):0;}if(p.kind==='rover')model.rotation.y=p.moving?Math.sin(t*.3)*.2:0;if(p.selected!==last){originals.forEach((mat,m)=>m.material=mat);originals.clear();model.traverse(o=>{if(o instanceof THREE.Mesh&&o.userData.part===p.selected){originals.set(o,o.material);o.material=highlight;}});last=p.selected??'';}controls.update();renderer.render(scene,camera);frame=requestAnimationFrame(animate);};animate();
  return()=>{disposed=true;cancelAnimationFrame(frame);obs.disconnect();visibility.disconnect();renderer.domElement.removeEventListener('webglcontextlost',lost);controls.dispose();scene.traverse(o=>{if(o instanceof THREE.Mesh)o.geometry.dispose();});Object.values(mats).forEach(m=>m.dispose());highlight.dispose();grid.geometry.dispose();(grid.material as THREE.Material).dispose();renderer.dispose();renderer.domElement.remove();};
 },[props.kind,flat]);
 return <div className="robot-scene-shell"><div className="robot-canvas" ref={mount} role="img" aria-label={props.lang==='sk'?'Model robota. Potiahnutím otočíš 3D pohľad.':'Robot model. Drag to rotate the 3D view.'}>{(failed||flat)&&<RobotDiagram {...props}/>}</div><button className="scene-mode button" onClick={()=>setFlat(!flat)} aria-pressed={flat}>{flat?'3D':'2D'}</button>{failed&&!flat&&<span className="scene-mode-note">{props.lang==='sk'?'Interaktívna 2D schéma':'Interactive 2D diagram'}</span>}</div>;
}
